// 0075 · The SOP: how the team operates The One, step by step, in the format
// of the Tech Locator Map SOPs (document control, role purpose, scope, who
// can use it, definitions, numbered procedures with notes and tables, success
// metric, revision history drawn from the migration ledger, sign-off).
//
// Every quoted label is the one on screen. WHEN A SCREEN CHANGES, CHANGE ITS
// STEP HERE.

import type { SopDocument } from './types';

export const SOP: SopDocument = {
  title: 'The One — Standard Operating Procedures',
  subtitle: 'Work-order, quote, vendor and payment platform for Seamless FM (Byblos Vista)',
  control:
    'This SOP defines how a work order is received, dispatched, quoted, approved, fulfilled, paid and invoiced in The One, who performs each step, which screen and button does it, and the rules the system enforces along the way. It is generated from the application itself: the procedures are kept beside the code, and the appendix (statuses, fields, roles, automations, integrations) is read from the live instance when this page opens.',
  purpose: [
    'The One is the single system of record for every work order Seamless FM runs on behalf of its clients: it receives the job from the client\'s system or by hand, finds the technician, logs the visits, builds and approves the quote, pays the technician, invoices the client and keeps the client informed, with every action recorded.',
    'Four kinds of people operate it. Managers (Team Lead, Assistant TL, Account Manager, Admin) accept work, approve quotes, payments and status changes, and set the rules. Dispatchers (OM, Senior OM, OM Under Probation, Ops Coordinator) find technicians, run visits and move the job. The Operations Admin drafts work orders typed in by hand and keeps the client systems in step. Accounts (Accounts Payable, Accounts Receivable, VR Officer, Sales) pay, audit, invoice, recruit vendors and watch their clients.',
    'Trust is tiered. A probation dispatcher requests status changes and cannot change the assignee; a senior dispatcher builds quotes; a manager decides. What each role may do is set in Admin › Roles and can be adjusted per person by a super admin.',
  ],
  scope:
    'This SOP covers signing in, the sidebar and top bar, receiving and accepting work orders, drafting them by hand, working the list, running a work order (vendor, visits, status, flags, messages, calls, photos, sign-off), quoting, parts and purchasing, completing the job, paying technicians, auditing and invoicing, the Approvals inbox, vendors and the technician map, sites, assets and clients, planned maintenance, client updates, dashboards and Pulse, the assistant, and every control of the Admin console.',
  whoCanUse:
    'Only people with a row in Admin › Users can sign in, with their Byblos Vista Microsoft account. A byblosvista.com account that is not on file enrols itself as OM Under Probation on first sign-in and is promoted by a super admin; any other address must be invited first. Super admins (Elise, Jordan Brown, Jeff S, Jack) pass every check.',

  terms: [
    { term: 'Work order (WO)', definition: 'One job for one client at one place. Identified by its WO # (the client\'s number when it came from their system).' },
    { term: 'Client CMMS', definition: 'The client\'s own maintenance system (Ecotrak, Corrigo, ServiceChannel). Work orders come from it; approved quotes and status changes go back to it once the connector is live. Which one a work order came from is the Client Portal Type field.' },
    { term: 'Dispatcher', definition: 'An OM, Senior OM, OM Under Probation or Ops Coordinator: the person assigned to run the work order (the Assignee).' },
    { term: 'Technician / vendor', definition: 'An external subcontractor who does the work. A VR vendor is a company the Vendor Relations team recruited; a technician is someone a dispatcher has worked with. Both are vendor records.' },
    { term: 'Status and phase', definition: 'The status is where the work order sits (Open, Assessment Sched, Waiting for Quote, …); statuses are grouped in phases (Open, Active, Pending, Done, Closed) that are the list\'s tabs. The system imposes no order between statuses; only the gates and the Ecotrak check can refuse a pick. Admin edits both.' },
    { term: 'Gate', definition: 'A rule that refuses a status until the record is ready: Quote Ready needs a quote, the parts statuses need Parts Required, Done / Incurred needs a completed visit, the Cost, a quote and an approved after photo (or a before photo and a sign-off for Bill For Incurred).' },
    { term: 'Request mode', definition: 'A role that cannot change a status directly picks one and a request goes to a manager in Approvals.' },
    { term: 'NTE', definition: 'Not-to-exceed: the client\'s ceiling for the job. Cost above it raises an NTE override task that holds the quote and the payment until a manager decides.' },
    { term: 'Visit (CICO)', definition: 'One technician visit with its check-in and check-out stamps: Assessment, Job or Return trip. A check-in moves the work order On Site.' },
    { term: 'Quote clock', definition: 'Quote Due Date: 48 business hours after the assessment check-out, skipping weekends and the holiday table, Chicago time.' },
    { term: 'Yoda', definition: 'The payment tool Accounts Payable hands approved technician payments to (Send to Yoda).' },
    { term: 'Scope ("Only theirs")', definition: 'A role or person who sees only the work orders assigned to them, widened by billing entities, assigned clients, or narrowed to a list of sites.' },
    { term: 'Super admin', definition: 'One of the four named people who pass every permission check and alone can adjust one person\'s permissions, restrict a person to sites, or view as someone else.' },
    { term: 'Audit log', definition: 'The append-only record of every change (who, when, before, after). Nothing in it can be edited or deleted.' },
    { term: 'Service principal', definition: 'A named system account (Ecotrak sync, Quo, Planned maintenance, Client updates, Email escalations, Dispatch, Vendor portal, Automations) that signs what the system does by itself.' },
  ],

  procedures: [
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 1,
      title: 'Signing In',
      lead: 'Access is Microsoft sign-in only; The One holds no passwords.',
      who: ['Everyone'],
      where: 'The sign-in page',
      needs: [],
      blocks: [
        { kind: 'steps', items: ['Open the site and click **Sign in with Microsoft**.', 'Use your Byblos Vista Microsoft account; any other account is rejected unless it has been invited in Admin › Users.', 'You land on the Dashboard, or on the page whose link you followed. The Work Orders list is the first sidebar item below Pulse; the home route "/" opens it for roles that have work orders.'] },
        { kind: 'note', title: 'NOTE', text: 'A session is a row on the server (12 hours by default). Sign out with the button in the sidebar footer next to your name; it also ends your Microsoft session. A disabled account loses its sessions immediately. A permission change takes effect on the next request, not the next sign-in.' },
        { kind: 'note', title: 'FIRST SIGN-IN', text: 'A byblosvista.com account that is not on file is created as OM Under Probation and logged. Ask a super admin to set your role in Admin › Users. A failed sign-in returns you to the sign-in page with the reason ("Microsoft rejected the sign-in", "That sign-in link has expired", or that you have not been invited).' },
      ],
    },
    {
      n: 2,
      title: 'Finding Your Way',
      lead: 'One frame around every screen: the sidebar is your job, the top bar is your tools.',
      who: ['Everyone'],
      where: 'Every page',
      needs: [],
      blocks: [
        { kind: 'bullets', items: [
          '**Sidebar**: Dashboard, Pulse, Work Orders, Vendors, Sites, Assets, Clients, Quotes, Payments, Incoming Work Orders, Planned Maintenance, Maintenance, Approvals, Receivables, Contracts, Purchasing, Client Updates, Admin (a group that opens to its sections). You only see the items your role includes. Collapse it to an icon rail with the arrow or **Ctrl/Cmd+B**. Badges: Work Orders (the count of the list you are looking at), Approvals (what waits on you: to decide plus to acknowledge), Incoming Work Orders (to accept plus open drafts). The footer shows who you are acting as and **Sign out**.',
          '**Search** (top bar, **Ctrl/Cmd+K**): a command palette over Pages, Work orders (WO #, client reference, title, client, city, state, trade), Quotes and, for super admins, People; arrow keys and Enter open a result.',
          '**Bell**: "For you" notices (a task given to you, a review to make, a decision on your request, a work order assigned to you, an insurance date expiring, a permit, a purchase request, a dispatch answer, an asset request) above the Pulse pings; **Mark all read**; **Open the Pulse**.',
          '**Sparkle**: the assistant. Ask a question about the data ("which of my work orders are waiting for parts?") or about the app ("how do I request a status change?"). It answers only from what you may see and never changes anything.',
          '**Sun / moon**: switch between the Blackout and Daylight Dispatch themes for this browser (the first visit follows your operating system).',
          '**Viewing as** (super admins): act as another person to see what they see; **Myself** ends it; it is recorded in the audit log, and the admin console still reads you.',
        ] },
        { kind: 'note', title: 'LOCKED WITH A REASON', text: 'A page or button you may not use is shown locked with a sentence saying why and who to ask ("This section is not available to you — Your role does not include it. Ask a super admin if you need access."). Nothing fails silently.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 3,
      title: 'Receiving and Accepting Work Orders',
      lead: 'Every work order the Ecotrak sync or the CSV import creates without a dispatcher waits on Incoming Work Orders until a manager accepts it and names one, or rejects it.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Incoming Work Orders › To accept',
      needs: ['approvals/intake view', 'approvals/intake approve'],
      blocks: [
        { kind: 'p', text: 'Work orders arrive from the Ecotrak sync (manual trigger; Admin › Integrations switches it), from the CSV import on the Work Orders list, from a planned-maintenance schedule, from an OP Admin draft or from the Add work order form. Only the first two can arrive unassigned and enter this queue; schedules, drafts and the form hand the work order over already assigned.' },
        { kind: 'sub', title: 'Accept and assign' },
        { kind: 'steps', items: [
          'Open **Incoming Work Orders**. Rows are oldest first and read "New work order · From Ecotrak | CSV import · <trade> · accept and assign, or reject".',
          'If the row says **Fill before assigning: …**, click **open the work order** and fill the listed fields on **All fields**. The 13 intake fields are Received on, Due date, SLA, Address, City, State, Zip code, Store, Trade, WO description, FM, Comp and Client NTE ($0.00 counts as filled).',
          'Click **Accept**. In "Accept this work order?" pick the dispatcher under **Assign to** (Dispatchers first, then Everyone else). Click **Who\'s available?** to see the people listed on this client (or **All dispatchers**) with the number of active work orders each holds across every client; **Fewest first / Most first** flips the order; the chevron shows their work orders per status; clicking a name picks them. Add a **Note** if useful.',
          'Click **Accept and assign**. The work order is assigned as your own edit (audited, "Assigned to <name>"), appears in that dispatcher\'s list, a sign-off sheet is drawn for it, and an internal comment records the decision.',
        ] },
        { kind: 'sub', title: 'Reject' },
        { kind: 'steps', items: ['Click **Reject**, type the reason in "Reject this work order", click **Reject with note**.', 'The work order moves to Cancelled / Postponed and leaves the queue.'] },
        { kind: 'note', title: 'RULES', text: 'Accept stays locked while an intake field is missing (rule 11.1.1). The assignee must be an active person on file. Filling the Assignee by hand on the work order, or cancelling it, closes the acceptance by itself. Dispatcher tiers cannot change the Assignee (rule 8.5.4); a manager can, from the People tab. **Claim** takes a row for yourself. A reject needs a "Cancelled / Postponed" status to exist (Admin › Custom fields).' },
      ],
    },
    {
      n: 4,
      title: 'Drafting a Work Order by Hand (WO Intake)',
      lead: 'The Operations Admin\'s staging area for jobs that come by email or phone.',
      who: ['Operations Admin', 'Admin'],
      where: 'Incoming Work Orders › Drafts',
      needs: ['intake view', 'intake create', 'intake edit'],
      blocks: [
        { kind: 'steps', items: [
          'On **Drafts** click **New work order**.',
          'Type the **WO #** ("The client\'s work order number") and fill the fields: the same 13 intake fields plus Client and the **Assignee** ("Pick the dispatcher it goes to"; use **Who\'s available?**).',
          'Click **Save draft** to keep it; the row shows what is **Still to fill** and reads **Draft** or **Ready to submit**.',
          'When it reads **Ready to submit**, click **Submit & assign**. The work order is created in status Open, already assigned, with its SharePoint folder when that switch is on; the draft is marked submitted and you land on "Submitted" with **Open the work order** / **Back to the drafts**. No acceptance is raised: your assignment is the handoff.',
          'To drop a draft: **Discard**, then **Yes, discard** in "Discard this draft?". The row is kept as discarded.',
        ] },
        { kind: 'note', title: 'RULES', text: 'Submit refuses a WO # that already exists (even in Trash) and refuses while a required field or an active assignee is missing (rule 14.2.2). A submitted or discarded draft can no longer be edited.' },
      ],
    },
    {
      n: 5,
      title: 'Adding a Work Order from the List',
      lead: 'The same act without the draft, for anyone with the create right.',
      who: ['Operations Admin', 'Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Work Orders › Add work order',
      needs: ['work_orders create'],
      blocks: [
        { kind: 'steps', items: [
          'Click **Add work order**. Optionally **Start from a template…** ("Filled in from <name>. The WO # is still yours to type.").',
          'Type the **WO #** ("The number the client knows this job by"). A number in use is refused as you type ("That number is already taken"; a trashed one says so, with **Open it**).',
          'Optionally pick a **Site** and an **Asset**; the site fills the client, store and address while those fields are empty; an asset under warranty shows "Under warranty — check before quoting."',
          'Fill the sections (Identity, Where, What is wrong, When it is due, Money and people, More details). Fields marked * are required, and the footer lists what the form **Still needs** until it reads **Ready**. Which fields appear, and which are required, is set in Admin › Custom fields (the **Add work order** column) and Admin › Settings (layouts per client or trade; a banner says when one applies).',
          'Optionally add files under **Photos and files** (up to 10); they upload once the work order exists and wait for approval like any upload.',
          'Click **Create work order** (or **Create and upload N files**). **Save as template** keeps the filled form for next time ("The WO # and the asset are not saved"); **Share it with everyone** needs the Custom fields edit right.',
        ] },
        { kind: 'note', title: 'DUPLICATES', text: 'The WO # is identity and is refused when taken. "Possible duplicates" (open work on the same asset, the same site and trade within 30 days, the same store and trade within 30 days) is a warning with links, never a block: "Carry on if this is a different job."' },
        { kind: 'note', title: 'WHAT HAPPENS NEXT', text: 'The work order starts in Open, its SharePoint folder is filed when that switch is on, the dispatch cascade starts when Admin set it to start by itself, the create automations run, and the Assignee is written as an audited edit. A form-created work order never enters the acceptance queue.' },
        { kind: 'note', title: 'IMPORT', text: 'To load many at once: **Import**, **Choose file**, match each column under **Match the columns** (targets include WO # (match key), Status (by name), Home list (by name); "Ignore this column"), choose **Create and update** or **Only create**, **Preview** (a dry run, required), then **Import N rows**. A row whose WO # exists updates that work order; rows with errors are left out and the rest still import; up to 2,000 rows in one transaction. Imported rows without an assignee go to the acceptance queue.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 6,
      title: 'Working the Work Orders List',
      lead: 'Arrange the list for your job once; it remembers.',
      who: ['Everyone with work orders'],
      where: 'Work Orders',
      needs: ['work_orders view', 'work_orders/export view for Export'],
      blocks: [
        { kind: 'bullets', items: [
          '**Tabs** along the top are views: All work orders, Due Today, Escalation Tracker, then saved views (pushpin = pinned, user icon = shared by a colleague, globe = your shared view). Click a row or its WO number to open it.',
          '**Segments** (All, Open, Active, Pending, Done, Closed, …) add phases together; **All** clears. A saved view\'s own phases are locked while you are not editing it.',
          '**Chips** Status, Assignee, FM, Comp, AM: tick values (**Select all / Clear all**, a search box when there are many); the Status chip narrows to exact statuses.',
          '**Filter › Add filter**: any field, a test (is, is not, contains, is set, is greater than, is between, is any of, …) and a value; **Match all / Match any**; half-written rules are held, not applied. **Group**: by any field ("Grouped by <field>", counts per bucket, **Select group**); **No grouping** undoes it. Click a column header to sort (ascending, descending, off; empties last); **Sort by breach** puts the worst obligation first. **Columns**: reorder or remove under **Shown**, add under **Add a column**, **Reset** to the default eight.',
          '**Save view**: name it (**Save this view**), tick **Share with the team** if everyone should have it, **Save**. A saved view opens read-only; the pencil enters **Editing** mode (**Cancel**, **Save "<name>"**); **Reset** returns to the view as saved. The trash icon then **Delete view** removes it for everyone it is shared with. The pushpin makes it your landing view.',
          '**Export**: a CSV of the filtered rows in the shown columns (up to 10,000; logged).',
          '**Status pill** in a row: change (or request) the status without opening the work order; the gates and the Ecotrak check are enforced on the click (the tags are drawn on the work-order page).',
          'Your working arrangement (not a saved view) is kept in this browser and restored on reload.',
        ] },
        { kind: 'sub', title: 'Due Today (the daily to-do)' },
        { kind: 'table', head: ['Segment', 'What it lists for the picked day'], rows: [
          ['All', 'Everything the other four list.'],
          ['Escalations', 'Due Date on or before the day and not yet scheduled or on site (Job Sched and On Site (Job) are exempt).'],
          ['Scheduled', 'Scheduled Date on the day.'],
          ['Quote', 'Quote Due Date on the day, plus overdue quotes while the status is still before Quote Ready (when the day is today).'],
          ['Parts arriving', 'Parts Arrival Date on the day.'],
        ] },
        { kind: 'p', text: 'Pick **Today**, **Tomorrow** or **Any day**; "today" rolls over at midnight. The columns are fixed (WO #, Client, Trade, Status, Assignee, Due Date, Scheduled Date, Quote Due Date, Parts Arrival Date); Filter and Save view are hidden here, Group and Sort by breach still work.' },
        { kind: 'sub', title: 'Bulk actions' },
        { kind: 'steps', items: [
          'Tick rows, the header box (this page), shift-click a range, or **Select all N matching** (up to 5,000).',
          '**Edit**: **Add a field** (client, trade, city, state, billing entity, priority, NTE, date received or a custom field), set the value (blank clears), optionally **Move to a list**, **Apply to selection**. Visit-owned fields, Quote Due Date, and a Cost or Total Invoiced the system has written are refused with the reason.',
          '**Set status**: picks a status for the whole selection (hidden for request-mode roles). If any row would fail a gate, the whole move is refused and the message names the work orders. The Ecotrak check does not run on a bulk move.',
          '**Enroll**: puts the selection (up to 500) through an automation: a **Manual** rule, or an **Automatic (re-run by hand)** one; the result says how many were applied, are waiting on the rule\'s timer, were skipped or failed. A paused rule is refused.',
          '**Delete**, then **Move to Trash**: they disappear from everyone\'s list; an administrator can restore them from Admin › Trash.',
        ] },
        { kind: 'note', title: 'SCOPE', text: 'A person limited to their own work orders sees a "Yours only" or "Yours + <Comp>, <client>" chip; a work order outside their scope answers "<WO> is not assigned to you", and a bulk edit or delete must be wholly inside it.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 7,
      title: 'Running a Work Order: Vendor, Visits and Status',
      lead: 'The dispatcher\'s core loop: find the technician, log the visits, move the status.',
      who: ['OM (dispatcher)', 'Senior OM', 'OM Under Probation', 'Ops Coordinator'],
      where: 'The work-order page: header, action bar, People and CICO tabs',
      needs: ['work_orders edit', 'work_orders/fields/cico edit', 'vendor_map view / create', 'work_orders/status edit or create', 'work_orders/calls create', 'work_orders/fields/cico/fields.24. Sign-Off Link edit (sheets)', 'work_orders/pdf view', 'work_orders/tabs/money view (Increase NTE)'],
      blocks: [
        { kind: 'sub', title: 'A. Find and hire the technician' },
        { kind: 'steps', items: [
          'Open the **People** tab. The **Suggested vendors** card lists the top vendors for this work order: the hand-picked preferred vendors for the client / trade / state / city first (**Preferred #n**), then the best fit by trade, coverage, client history, distance, compliance, jobs and rate. Blacklisted vendors never appear. **Hire** or **Call** from the row.',
          'Or click **Find a technician** on the **Technicians** card to open the map centred on the work order (radius set by Admin). Filter by **Trade**, **Availability** (Emergency same day, After hours, Weekends, Holiday emergency) and **Show** (VR vendors, Technicians or My technicians, Local, Statewide, Nationwide, Top 5 technicians, Hide blacklisted). Pin shape is the source; pin colour is the trade; tags read Hired, Preferred #n, Blacklisted, Yours, "N mi".',
          'Click a pin for the card: phones (tap to call), rates, trip charge, response time, coverage, compliance, **Add note**, **Blacklist**. Click **Hire for <WO#>**. A missing or expired COI warns; it never blocks. The technician is recorded on the work order and joins your own technician list. **Take off <WO#>** releases them (the record and its visits stay).',
          'Someone not on file? **Add a technician** (Name, Phone, City, State, ZIP, Trade, "Hire for <WO#> straight away"). A phone already on file links that record to you instead.',
          'To phone: **Call** in the header ("Call from <WO#>"), pick **Who** (from the map, the latest visit, the Quo line, or Another number), choose **Just call** or **Call and draft a quote**, click **Call via Quo**. The Quo desktop app dials; the call, transcript and summary come back to the **Calls** card on the Messages tab.',
          'Optionally **Assign vendor** on the action bar names the one responsible vendor for the record (a blacklisted vendor is refused).',
        ] },
        { kind: 'sub', title: 'B. Log the visits (CICO)' },
        { kind: 'steps', items: [
          'On the **CICO** tab click **New visit**.',
          'Pick the **Visit type** (Assessment, Job or Return trip), the **Technician** (free text, or anyone on file: hired first), the **Phone**, the **Method** and **Method detail** (pre-filled from the FM). Click **Log visit**.',
          'When the technician arrives, set the row\'s status to **Checked in**. The time is stamped and the work order moves by itself to **On Site (Assessment)** or **On Site (Job)** (rule 2.2.2), from whatever status it was in and whatever your status rights. Optionally record the location: **Use this device\'s location** or **Type coordinates**; the result reads "<place> · N ft from the pin"; **Clear** removes it.',
          'When they leave, set **Checked out** (or **Checked out · return trip needed**). An Assessment check-out stamps **Quote Due Date** (48 business hours). A Job check-out never does.',
          'Correct a stamp with the pencil (**Save visit**; "A corrected time keeps its history"); see **History of this visit**; delete with the trash icon ("The old check-in/out fields will read the visit before it.").',
        ] },
        { kind: 'note', title: 'SIGN-OFF SHEET', text: 'The sheet was drawn when the work order was assigned (the panel at the foot of the CICO card; it needs a Comp that names a layout and file storage on). Click **Send to tech**, pick the technician\'s number (hired technicians, visit technicians, the latest visit, or **Another number**) and click **Text the sheet** (Quo API) or **Open in Quo** (the Quo desktop app sends it). When the signed copy is texted back it is filed as a pending Sign-off attachment, Sign-Off Link is set and the chip reads **Signed copy received**; approve it on Overview › Photos like any upload. If several sheets could match, each candidate shows **Yes, file it here / Not this one**. **Redraw with current details** appears when the number or address changed (**Details changed**); **New sheet** replaces the sheet and its link.' },
        { kind: 'sub', title: 'C. Move the status' },
        { kind: 'steps', items: [
          'Click **Change status** in the header (or the status pill in the list) and pick the next status. Roles in request mode see **Request status change** instead: the pick raises a request a manager decides in Approvals ("Request for <status> sent for approval"), and the decision shows on the header banner: **Continue** after an approval; **Request again** or **Understood** after a rejection. **Withdraw** an open request from Approvals › My requests.',
          'A pick the record is not ready for is tagged and refused with the reason:',
        ] },
        { kind: 'table', head: ['Status', 'Needs', 'Tag in the menu'], rows: [
          ['Quote Ready', 'A quote with at least one line item or scope line.', 'Needs quote'],
          ['Waiting for Parts, Please Order Parts', 'The Parts Required field written (Parts tab).', 'Needs parts'],
          ['Done / Incurred', 'A visit checked in and out; Cost; a quote with data; an approved After photo (Bill For Incurred: an approved Before photo and an approved Sign-off).', 'Needs check-out / Needs cost / Needs quote / Needs after photo / Needs sign-off; Not ready for several'],
          ['Any', 'A move Ecotrak would refuse from the work order\'s Ecotrak status.', 'Ecotrak (a warning, unless the site is set to block)'],
        ] },
        { kind: 'sub', title: 'D. The action bar' },
        { kind: 'bullets', items: [
          '**Pause** ("Why is it paused?") / **Resume**: a marker on the record; no clock stops (rule 2.4.4). Not on a cancelled work order.',
          '**Add ETA** / **Change ETA**: **Expected on site**, a note, **Save ETA**; **Clear the ETA**.',
          '**Tag**: a **Tag** (suggestions offered) and a **Reason**, **Add the tag**; remove from the chip.',
          '**Increase NTE** ("Ask for a higher NTE"): **New NTE** (above the current one) and **Why more is needed**, **Send the request**. A manager decides it on the **Cost breakdown** tab (**Approve — set the NTE to $X** / **Reject**); you may **Withdraw** it; one open request at a time; both sides are told by a notice. These requests are not in the Approvals inbox.',
          '**Complete service** / **Edit completion**: **Completion note**, **Fault code — what was wrong**, **Action code — what was done**, **Is this a temporary fix?**; it records the completion and does not move the status; **Clear the completion** undoes it.',
          '**Cancel work order** ("Why is it cancelled?") / **Reopen**: moves to the Cancelled status and ends an open pause.',
          '**Save as PDF**: **Work order** ("The main fields, as set in Admin › Settings") or **Request** ("Client, site and what they asked for"), in the billing entity\'s branding.',
        ] },
        { kind: 'sub', title: 'E. The other record tabs' },
        { kind: 'bullets', items: [
          '**Checklist**: type a step (or paste several, one per line) and **Add**; tick steps as done; **Apply** a job plan; services and consumables used.',
          '**Cost breakdown**: revenue and cost bases, margin, **Open the quote**, the NTE increase requests.',
          '**Timelog**: open time, response time, time on site, time in each status, the visits with their locations, pauses; **Start a timer** / **Stop** / **Log time** for technician time.',
          '**Related**: approvals on this work order, work permits (**Write a work permit**), same asset, same site.',
          '**Site**: the **Site record** block — **Link** / **Change** / **Unlink** a site, choose the asset; access notes under "Getting in".',
        ] },
      ],
    },
    {
      n: 8,
      title: 'Flags, Messages, Photos and Files',
      lead: 'What everyone else sees about the job.',
      who: ['Dispatchers', 'Managers', 'Operations Admin'],
      where: 'Header, Flags tab, Messages tab, Overview › Photos',
      needs: ['work_orders/comments create / edit', 'work_orders/comments/client create', 'work_orders/attachments create / approve', 'work_orders/history view'],
      blocks: [
        { kind: 'sub', title: 'Flags' },
        { kind: 'bullets', items: [
          '**Emergency**: the checkbox on the Flags tab (or All fields). Turns the work order red in every list, queue and board.',
          '**Mark as Escalated** in the header (managers; dispatcher tiers see the field read-only). Turns it amber, pins it at the top of the Approvals inbox and lists it on the Escalation Tracker tab. **Escalated · Clear** removes it. An email tool can set it through the escalation webhook (never clear it) when that integration is on.',
        ] },
        { kind: 'sub', title: 'Messages' },
        { kind: 'steps', items: [
          'On the **Messages** tab choose **Internal** ("the team only, never the client") or **Client-visible** (what the client\'s system will receive, once one is linked).',
          'Type (up to 4,000 characters) and click **Post internally** or **Send to client**. A client-visible message queues for the client\'s CMMS and the bubble says "Queued …" until it is sent.',
          'Edit your own message with the pencil only until it is sent (the lock reads "Sent to the client — it can no longer be edited"); editing may change its visibility. A note the client wrote in their system is never editable.',
          '**Technician texts** (the Quo thread) sit on the same tab: **Send text** sends from your claimed Quo line; the rail shows the technician and the conversation.',
        ] },
        { kind: 'sub', title: 'Photos and files' },
        { kind: 'steps', items: [
          'In the message box click the camera (**Add photo**) or **Attach file**. Photos are shrunk in the browser first; the cap is 4 MB; PDFs, images, text, CSV and Office files are accepted.',
          'Every upload waits for approval ("Hidden from everyone else until approved"). On **Overview › Photos › Waiting for approval**, a reviewer picks **What is it?** (Before photo, After photo, Sign-off, Other), optionally renames the file, then **Approve** or **Decline**. Until then only reviewers and the uploader can see it.',
          'Approved photos group by kind and, when the SharePoint switch is on, are copied into the work order\'s SharePoint folder.',
        ] },
        { kind: 'note', title: 'WHY', text: 'Done / Incurred needs an approved After photo (or Before photo plus Sign-off for Bill For Incurred): rules 1.3.1 to 1.3.4 and 11.3.4. The "Needs after photo" / "Needs sign-off" tag clears the moment the file is approved.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 9,
      title: 'Quoting',
      lead: 'One quote per work order, due 48 business hours after the assessment, priced from the client contract.',
      who: ['Senior OM', 'Team Lead', 'Assistant TL', 'Account Manager'],
      where: 'The Client quote card › the quote builder; Quotes',
      needs: ['quotes create', 'quotes edit', 'quotes approve'],
      blocks: [
        { kind: 'steps', items: [
          'On the work order\'s **Finances** tab, **Client quote** card, click **Create quote**, then **Create quote** again in the builder. The number (Q-<entity>-<year>-<n>) is issued, the client contract\'s rates are snapshotted and Bill to is pre-filled with the client.',
          'Fill **Tech reported that…** (required) and at least one scope line under "Required is to…" (Enter adds a line). **Add line** for priced items (Type, Description, Qty, UOM, Unit price, Markup %, Tax %, Day, OT); **Add option** for the alternatives the client chooses between — each needs an **Option name** and an **Option narrative**, and only options with **Include in summary** on count in the Grand Total. Pick a tax rate with **Apply a rate…** if sales tax applies. It saves as you type (the chip reads Draft saved · n ago).',
          'Fix anything the red chip lists, then click **Submit for approval**. The quote appears in Quotes › Pending approval and in Approvals › Quotes.',
          'A manager clicks **Approve & Send to CMMS** in the builder (approve, then send; if sending fails the quote stays approved and the button reads **Send to CMMS**), or **Approve & send** on the Quotes list, or **Approve** in Approvals (approves only). To send it back: **Reject with note** in the builder or **Decline** on the list — a note is required, the quote returns to draft (even from approved) and its revision number goes up.',
          'Move the status to **Quote Ready**, then **Waiting for Approval** once it is with the client. **Print / PDF** prints the quote with the default template\'s letterhead and terms; the printed Total adds the sales tax and the page says the quote is valid for 30 days.',
        ] },
        { kind: 'note', title: 'GRAND TOTAL', text: 'Grand Total is the price of the options included in the summary plus their line tax. The Incurred lines ("Work already performed") are context and are not added twice; the invoice adds them later.' },
        { kind: 'note', title: 'AI DRAFT', text: 'From a call placed with **Call and draft a quote** that has a transcript, click **Draft a quote with AI** on the Calls card (needs the Claude integration on). The draft opens in the builder\'s own editors beside the transcript with its assumptions and missing information; adjust it and click **Submit quote**. Prices are never invented: the client price stated, the vendor cost plus the contract markup, the contract rate, or a listed gap at $0. A quote that already has content asks before being replaced; an approved or sent quote is never touched.' },
        { kind: 'note', title: 'HOLD', text: 'Approving and sending are locked while an NTE override task is open on the work order ("On hold — decide the NTE override under Approvals first"). Rejecting is never locked. Once approved, the quote is never re-priced.' },
      ],
    },
    {
      n: 10,
      title: 'Parts and Purchasing',
      lead: 'Parts are written on the work order before a parts status; bigger buys go through purchasing.',
      who: ['Dispatchers', 'Accounts Payable', 'Team Lead'],
      where: 'The Parts tab; Purchasing',
      needs: ['work_orders edit', 'purchasing/requests, rfqs, orders, budgets'],
      blocks: [
        { kind: 'steps', items: [
          'On the **Parts** tab write **Parts Required** (what, how many, where from) and the **Parts Arrival Date** when known.',
          'Move the status to **Please Order Parts** (AP orders) or **Waiting for Parts** (ordered). Both are refused while Parts Required is empty (rule 11.2.2). Due Today lists the arrival under **Parts arriving**.',
          'When parts arrive, schedule the job (**Job Sched**) and log the Job visit.',
        ] },
        { kind: 'sub', title: 'Purchasing (Purchasing in the sidebar)' },
        { kind: 'bullets', items: [
          '**Requests** (PR-n): **New request**, what is being bought, items (**+ Add a line**, each with a quantity above zero), optionally the work order; **Save as draft** or **Submit for approval**. A manager opens it and clicks **Approve**, or writes a **Note to the requester** and **Reject**; **Cancel the request**; **Back to draft** after a rejection. From an approved request: **Ask vendors for quotes** or **Raise a purchase order**.',
          '**Requests for quotation** (RFQ-n): items and vendors; **Mark as sent to vendors** (this records it; nothing is emailed; refused with no lines or vendors); **Record quote** for each vendor\'s answer; **Quotes side by side** marks the lowest and the fastest; **Close to quotes** / **Reopen** / **Cancel it**; **Award** on the chosen one drafts a purchase order (a blacklisted vendor cannot be awarded).',
          '**Purchase orders** (PO-n): **New purchase order**, pick the **Vendor** and **Items**, **Save as draft** (only a draft is editable); **Issue the order** (needs approve; refuses an empty or zero-value order); when goods arrive enter the quantities and **Save what arrived** (never more than ordered); **Close the order**. **Print / PDF** prints it. Cancelling an issued order needs approve, and is refused once anything was received.',
          '**Budgets**: cost centers (Code, Name) and AFEs (AFE number, Amount authorized, Title, Valid from / to). Spent = work-order Cost plus received orders not tied to a work order; Committed = issued orders still to arrive.',
        ] },
        { kind: 'note', title: 'RULE', text: 'A purchase order never changes a work order\'s Cost. Cost is the technician payments (SOP 12). Going over a budget or an AFE warns on the order and never blocks.' },
      ],
    },
    {
      n: 11,
      title: 'Completing the Job',
      lead: 'Done / Incurred is the soft close: the system checks the proof before it accepts it.',
      who: ['Dispatchers', 'Managers'],
      where: 'The work-order page',
      needs: ['work_orders/status edit or create'],
      blocks: [
        { kind: 'steps', items: [
          'Make sure the Job visit is **Checked out** on the CICO tab (rule 11.3.1).',
          'Make sure the **After photo** is uploaded and approved (SOP 8). For a Bill For Incurred job, a Before photo and the approved Sign-off instead (rule 11.3.4; the tag reads "Needs sign-off").',
          'Make sure the technician\'s payment request has been approved (SOP 12): **Cost** is the total of accepted requests and cannot be typed once the system has written it. A work order with no payment request still takes a typed Cost (rule 11.3.2).',
          'Make sure the quote has data (rule 11.3.3).',
          'Optionally **Complete service** on the action bar: completion note, fault code, action code.',
          'Change the status to **Done / Incurred**. When a client contract covering this work order has **Bill automatically on completion**, a proposed invoice appears for Accounts to confirm; a time-and-materials vendor contract proposes the vendor bill the same way (rule 6.4).',
        ] },
        { kind: 'note', title: 'RETURN TRIPS', text: 'If the job is not finished, check out as **Checked out · return trip needed** and move to **Return Trip Needed**; the next check-in moves it back On Site (Job).' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 12,
      title: 'Paying the Technician',
      lead: 'A request per payment, approved by the right tier, handed to Yoda, marked paid.',
      who: ['Dispatchers (request)', 'Team Lead / Assistant TL / Account Manager (approve)', 'Accounts Payable (process)'],
      where: 'The Payables tab; Payments',
      needs: ['payments create', 'payments approve', 'payments/process edit'],
      blocks: [
        { kind: 'steps', items: [
          'On the work order\'s **Payables** tab, **Payment requests** card, click **Request payment**. Pick the **Vendor record**, or type a name and phone ("Technician not in the vendor list? Enter a name and phone manually"); optionally **Add recipient** to pay someone other than the technician; fill **Purpose**, **Amount** (above $0) and **Method** (Zelle, ACH transfer, Check, Company card, Cash App), a note for AP, then **Submit payment request**. Receipts cannot be attached here yet.',
          'An approver opens **Payments › Needs approval** and clicks **Approve** then **Approve payment**, or **Reject**, gives the reason and clicks **Reject with note** (also possible after approval). The button is locked with the reason when the amount is outside the approver\'s tier (Admin › Settings › Approval tiers) or while an NTE override is open.',
          'Accounts Payable opens **Payments › To process**, clicks **Send to Yoda** (optional **Yoda reference**, e.g. YD-10422) and later **Mark paid**.',
        ] },
        { kind: 'table', head: ['Rule', 'What happens'], rows: [
          ['Cost follows the payments', 'Cost = the sum of accepted requests (approved, sent to Yoda or paid); rejecting one takes it back out, and rejecting the last one clears Cost.'],
          ['NTE override (1.5.2)', 'When Cost passes the client NTE an NTE override task lands in Approvals and holds Approve and Send to Yoda (not Reject or Mark paid) and the quote; it cancels itself once Cost is back under the NTE.'],
          ['Tiers (6.2.3)', 'As seeded: under $500 anyone with the permission; $500 to $3,000 TL / ATL / AM / Admin; over $3,000 TL / Admin. Admin › Settings edits the bands; super admins are never restricted.'],
        ] },
        { kind: 'sub', title: 'Vendor bills and credit notes' },
        { kind: 'steps', items: [
          '**Payments › Vendor bills › Record bill**: the work order id (from its address bar), **Vendor**, **Their invoice #**, dates and lines; **Record bill**. A chip warns when an invoicing rule trips (number missing or reused, over the work order\'s Cost, vendor not on the work order, billed before completion or late); warnings never block.',
          '**Approve** (payments approve, within the amount tier), **Mark paid** (payments/process edit), or **Dispute** with what is wrong ("Say what is being disputed"; **Resolve** returns it to received). Record, dispute, resolve and void need the request right. **Credit note** raises a credit against it (CN-n): approved as written at or under the threshold in Admin › Vendors & map, otherwise an approver is told.',
        ] },
      ],
    },
    {
      n: 13,
      title: 'Auditing and Invoicing the Client',
      lead: 'A pristine record first, then one invoice per work order from the approved quote.',
      who: ['Accounts Receivable', 'Admin'],
      where: 'Receivables › Audit and Invoicing',
      needs: ['invoicing view', 'invoicing create', 'invoicing edit', 'invoicing approve'],
      blocks: [
        { kind: 'sub', title: 'Audit (prototype)' },
        { kind: 'steps', items: [
          'Open **Receivables › Audit**. Lanes **All · Major · Minor · Clean** show "Auto-check results" and "Findings" per completed work order with a suggested QC.',
          'Fix what the checks flag on the work order (**Open work order**), then tick **GTG**, **Elise**, **Admin** and **Quote**. A clean, ticked work order shows "Clean release — this WO is in Invoicing → Ready to invoice"; move its status to **Ready to Invoice**.',
        ] },
        { kind: 'note', title: 'PROTOTYPE', text: 'The audit tab is still a prototype: its findings are sampled, not read from the record or from SharePoint and ClickUp ("External systems are stubbed in this prototype"), and the four ticks live in this browser only — they are not saved or audited. Treat it as the shape of the audit, not its verdict.' },
        { kind: 'sub', title: 'Invoicing' },
        { kind: 'steps', items: [
          'On **Invoicing › Ready** click **Raise invoice**. The draft is built from the approved quote (incurred plus the options flagged for the summary, overtime folded in) or, with no quote and a T&M contract, from hours on site plus the trip charge, else a single line at Total Invoiced or the NTE. The lines are the prefill; there is no line editor on screen yet.',
          'Click **Send** (needs approve; the amount tier applies; a zero total cannot be sent). The number (<entity>-<year>-<n>) is fixed, the lines are frozen and the due date is 30 days. Move the status to **Invoiced Not Paid**: Total Invoiced is stamped from the quote.',
          'When the client pays, click **Mark paid** (needs edit) and move the status to **Invoiced**. Void and reopen exist in the API only (no button yet).',
          '**Proposed**: when a contract has **Bill automatically on completion**, completion drafts a proposal; **Confirm** files the invoice with exactly those lines, **Dismiss** ("Why not? (optional)") drops it.',
          'Print at the invoice\'s **Print / PDF** with the default template; the work order\'s Finances tab offers **Send to client**, **Mark paid** and **Open in Receivables** too.',
        ] },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 14,
      title: 'The Approvals Inbox',
      lead: 'Every yes-or-no the system needs from a manager, in one place, oldest first.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Approvals',
      needs: ['approvals view', 'approvals/nte, status, reviews approve', 'quotes approve', 'payments approve'],
      blocks: [
        { kind: 'table', head: ['Section', 'What waits there', 'Deciding it does'], rows: [
          ['NTE increases', 'NTE override tasks raised when Cost passes the NTE ("Cost $X is over the client NTE $Y by $Z"). The manual Increase NTE requests are decided on the work order\'s Cost breakdown tab, not here.', 'Approve releases the quote and the payment; Reject keeps the hold.'],
          ['Status changes', 'Requests from request-mode roles, with from → to, "Requested by <name>", and an Ecotrak tag when Ecotrak would refuse.', 'Approve moves the work order (the gate and the Ecotrak check run again); Reject (reason) sends it back.'],
          ['Manager reviews', 'Review tasks raised by automations (the section appears once one exists).', 'Approve / Reject with a note.'],
          ['Quotes', 'Quotes pending approval.', 'Approve quote (approves only: "Sending it … is a separate step in the quote builder") / Return this quote to draft with a note.'],
          ['Payments', 'Payment requests in requested.', 'Approve payment ("clears it for AP to send to Yoda") / Reject this payment with a note.'],
        ] },
        { kind: 'bullets', items: [
          'Lanes: **For me**, **Open**, **Done**, **My requests**. Filters **Entity / Client / Trade / For**; **Columns** adds Client, Waiting for, NTE, Cost, WO Due Date, For, Raised, Status; pages of rows, up to 500. Escalated rows pin to the top; open rows are oldest first and every decision is per row.',
          '**Claim** takes a task for yourself. **Approve** takes an optional **Note**; **Reject** needs the reason, then **Reject with note**. A locked verb says why ("Requires new work order approval rights", "On hold — the NTE override on this work order has to be decided first").',
          'Under **My requests**: **Withdraw** a request still open; after a decision click **Continue** (approved) or **Understood** (rejected) to clear it from the header banner. An approver may withdraw or acknowledge on the requester\'s behalf.',
          'Acceptances are not here: they have their own page, Incoming Work Orders (SOP 3). Approvals raise no bell notice; the badge is the signal.',
        ] },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 15,
      title: 'Vendors and Technicians (Vendor Relations)',
      lead: 'The One\'s own vendor network: records, documents, compliance, tasks, alerts and the coverage map.',
      who: ['VR Officer', 'Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Vendors (List, Board, Tasks, Alerts, Data quality, Performance, Coverage map)',
      needs: ['vendors view / create / edit / delete', 'vendors/documents create / delete', 'vendors/review approve', 'vendors/blacklist create / edit', 'vendors/lists create', 'vendors/import create', 'vendors/export view', 'vendors/portal view / edit', 'vendors/dispatch edit'],
      blocks: [
        { kind: 'sub', title: 'Add and maintain a record' },
        { kind: 'steps', items: [
          'Click **Add vendor**. Fill **Name** (required), **Kind** (VR vendor or Technician), the trade, **City**, **State** and a phone; **Add vendor**. "This may already be on file." warns of a likely duplicate (same name or phone; **Add anyway — flag as a possible duplicate** opens a review); "Still needed:" lists the required fields set in Admin › Vendors & map (by default Name, a phone, Email, Owner, City, State; **Add anyway — flag for review** opens a review that closes itself once filled). A new VR vendor starts NEW with you as its owner; a new technician starts ACTIVE.',
          'Open the vendor, **Edit**, fill rates, availability, coverage (radius, whole state, nationwide, other states), payment terms, contacts, priority; **Save changes**. The record is placed on the map from its ZIP or city.',
          '**Documents**: pick the type (W-9, MSA, Certificate of insurance with the company it names, Other document) and **Upload** (PDF, image or Word, 3 MB). A W-9 or MSA marks it received; a COI opens a compliance review. Any vendor editor ticks the six checks on the COI card (Certificate holder is correct, Additional insured is named, General liability meets $1M / $2M, Workers comp, Commercial auto, Waiver of subrogation); a reviewer decides **Approve** or **Send back** from Tasks. **Insurance dates** are added on their card (a newer date replaces the old one, which no longer counts).',
          '**Notes**: type a note; to blacklist, tick **Blacklist with this as the reason** and click **Mark blacklisted** (everyone sees the flag and the reason; the owner is told). **Clear blacklist** is a manager\'s decision (the blacklist edit right).',
          '**Log a call** (what was said, a summary, a recording link, an outcome that may set the status) and **Log an email** (a record of an email you sent from your own mailbox; The One does not send it).',
        ] },
        { kind: 'note', title: 'COMPLIANCE', text: 'The status is derived, never ticked by hand: EXPIRED when a current insurance date is past; REJECTED when the COI was sent back; APPROVED when W-9, MSA and COI are received and the COI approved; IN_REVIEW when some are in; MISSING_DOCS otherwise. A New / Interested / Ready vendor turns Active when approved. Hiring a vendor whose COI is missing or expired warns; it never blocks. A blacklisted vendor is never suggested, cannot accept a dispatch offer, cannot get a portal link and cannot be set as the responsible vendor; hiring from the map warns.' },
        { kind: 'sub', title: 'Work the queues' },
        { kind: 'bullets', items: [
          '**Tasks**: duplicate (**Keep both** / **Remove this one**), missing-information (**Acknowledge**) and COI reviews (**Approve** / **Send back** → a COI fix for the owner, **Mark fixed** re-raises the review) in one queue decided with the review right; personal tasks (**Add a task…**, **Mark done**); **Today\'s target** for nationwide / statewide vendors added by a rep.',
          '**Alerts**: every insurance date that counts (All / Expired / Within 2 weeks / Within a month). **Data quality**: duplicates by name, phone or email, records missing required fields (unusable values flagged), records not on the map.',
          '**Board**: records by status; drag a card or **Move to…**. **Performance**: jobs, SLA met / missed, recalls, temp. fixes, response hours, offers taken, billed, bill checks, for a date range.',
          '**List tools**: dropdown filters and chips, advanced filters (**Show vendors that match all / any of these**), **Columns**, **Save as a list** (Name; **Only me / Managers / Everyone with the Vendors section**), bulk edit of one field, **Export CSV**, **Look up a list** (paste phone numbers, names or emails).',
          '**Import**: choose VR vendors or Technicians and a CSV, map the columns (**Leave out**; a brand source for rows that name none), **Check the file**, choose how to treat duplicates (skip, skip and report, add flagged, fill in the record on file) and rows missing required fields (add flagged, or leave out), **Import N rows**; download the duplicates report. Bad cells are reported and left empty.',
          '**Coverage map**: every placed vendor, filtered by trade, state and status, for "where do we recruit next".',
        ] },
        { kind: 'note', title: 'VENDOR PORTAL', text: 'On a vendor, create an **Onboarding link** or a **Job portal link** (shown once; copy it and send it yourself; **Revoke** at any time). The vendor sees its offered, open and recently finished jobs in a fixed shape with no money or internal notes, can **Accept this job** / **Decline** an offer, **Give ETA**, and leave a **Note for the dispatcher** (copied to the work order), and can fill the onboarding form, which waits until one of us clicks **Accept and fill the record** or **Send back**.' },
        { kind: 'note', title: 'DISPATCH CASCADE', text: 'Off by default. When Admin allows dispatch offers, the People tab\'s **Dispatch offers** card lets you **Offer to preferred vendors**: the preferred vendors of the client / trade / state / city are offered the job in turn, each with the hours Admin set to answer; **They accepted** / **They declined** / **Stop**; accepting sets the responsible vendor. A new work order with no vendor is offered automatically only when Admin also ticked "Start by itself". Preferred vendors are rules in Admin › Vendors & map.' },
      ],
    },
    {
      n: 16,
      title: 'Sites, Assets and Clients',
      lead: 'The places, the equipment and the accounts.',
      who: ['Dispatchers', 'Operations Admin', 'Managers', 'Admin'],
      where: 'Sites, Assets, Clients; the Site card of a work order',
      needs: ['sites', 'assets', 'assets/requests', 'clients'],
      blocks: [
        { kind: 'bullets', items: [
          '**Site**: **Add site** (a name, or a client and a store number; address, type, ownership, managed by, billing entity, contact, hours, **Getting in**, **Boundary (feet)**, a hand-placed pin), **Edit**, **+ Building** / **+ Floor** / **+ Space**, **Add asset**, **Add the event** (Closure, Restricted access, Remodel, Incident, Inspection, Weather, Notice; **End today**; shown as a chip on the site\'s work orders while running), **Remove** (soft). The list has List · Map · Events views, filters and flags (With open work orders / No assets on file / Not on the map). On a site that came from Ecotrak the name, client, store number and address are locked. **Create sites from work orders** (preview, then **Create and link**) makes a site per place found in the history.',
          '**Asset**: **Add asset** (Site and Name required; category, type, manufacturer, model, serial, tag, where it stands, part of, status, installed on, warranty), **Edit**, **Record a reading** (Good / Fair / Poor / Critical, what was seen, the work order), **Remove**. Anyone with the request right can **Request a change** (Replace / Retire / Move, with why) or **Request a new asset** from Assets › **Requests**; a manager clicks **Approve — make the change** or **Reject** (why); the requester may **Withdraw**.',
          '**Client**: **Add client** (Name required, "Exactly as it is written on work orders"; code, account manager, contacts, billing, **Client portal**, payment terms, Active), **Edit**, make inactive. A client with work orders or sites cannot be removed ("Mark it inactive instead"), and a client in use can only change its capitals and spacing. The client page shows its sites, work orders, contracts and the SharePoint folder chip.',
          '**On a work order**: the **Site** tab\'s **Site record** block links a site (**Link** / **Change** / **Unlink**) and an asset; the address fields stay the work order\'s own text.',
        ] },
        { kind: 'note', title: 'SCOPE', text: 'Every work-order list inside a site or an asset follows the viewer\'s work-order scope. A person restricted to a list of sites (Admin › Sites & assets, super admins only) sees only those sites, their assets and their work orders; a site outside the list answers "That site is not one of the sites you have access to".' },
      ],
    },
    {
      n: 17,
      title: 'Planned Maintenance and the Maintenance Tabs',
      lead: 'Recurring jobs that raise their own work orders, and the plans, services, time and permits around them.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin', 'Dispatchers (view of Planned Maintenance and the tabs their role opens)'],
      where: 'Planned Maintenance; Maintenance',
      needs: ['planned_maintenance create / edit / delete', 'maintenance/assignment edit', 'maintenance/job_plans, services, time, permits'],
      blocks: [
        { kind: 'steps', items: [
          '**Planned Maintenance › New schedule**: **What is the job?**, the client, billing entity, store, site, address, trade, **Work order description**, **Client NTE**, **Dispatcher**, optional **Job plan** (its steps become the checklist), **How often** (Every N days / weeks / months / years), **First due on**, **Ends** (blank = open), "Raise the work order this many days ahead", **Active**; **Create schedule**.',
          'The schedule raises one work order per due date inside the lead window, as **PM Sched**, already assigned, with WO # <code>-<date>, its SharePoint folder and its job plan. It runs when the list opens, after saving, on **Raise now** (the next date, lead window or not), and daily by the server\'s cron. **Skip** records a skipped occurrence; **Delete schedule** keeps its work orders ("To stop it for a while instead, edit it and untick Active."). The code opens the history of what was raised.',
        ] },
        { kind: 'bullets', items: [
          '**Maintenance › Assignment**: pick **Unassigned**, **Everything open** or a person (each with open, emergency and past-SLA counts), tick work orders, choose in **Assign to…** (or **Nobody (unassign)**), **Assign**. Needs the assignment right and the work-order edit right; the selection must be in your scope.',
          '**Job plans**: **New job plan**, Name, Trade, Estimated minutes, Steps one per line, Services with quantities, **Active**; applied once from a work order\'s Checklist tab or by a schedule.',
          '**Services**: **New service**, Name, Code, Trade, Unit, Price per unit, Cost per unit. Services never feed Cost.',
          '**Time tracker**: time entries logged on a work order\'s Timelog tab (**Start a timer** — one running per technician — **Stop**, **Log time**; Labor / Travel / Waiting), summed by technician for a date range.',
          '**Work permits**: written on a work order\'s Related tab (**Write a work permit**: kind with pre-filled precautions, holder, first and last day, hazards; **Save as draft**, **Send for approval**); decided by someone with the approve right (**Approve** / **Reject** with a note); **Close the permit** when done; **Back to draft** after a rejection. Once requested only the precaution ticks move.',
        ] },
      ],
    },
    {
      n: 18,
      title: 'Keeping the Client Informed (Client Updates)',
      lead: 'A live tracker per client, shared by link, email or schedule, instead of a spreadsheet.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin', 'Dispatchers (view)'],
      where: 'Client Updates; /share/client-updates/<token> for the client',
      needs: ['client_updates create / edit / delete', 'client_updates/share edit'],
      blocks: [
        { kind: 'steps', items: [
          '**New tracker**: **Client**, **Tracker name**, a **Note for our team**; how the list reads (sections, order, the **Client note column**); adjust columns (**Add column**, each **Client sees it** or **Team only**, up to 40) and charts (**Add chart**, Bars / Donut, up to 8); **Create tracker**. Change it later under **Settings**; **Delete tracker** removes it.',
          'Type client-facing notes straight into the note column of a row (**Add a note**; Ctrl/⌘+Enter saves; it writes the work order\'s field, audited). The tiles (Work orders, Open, Waiting on the client, Open over 30 days, Completed last 30 days, NTE on open work) and the charts drill the list; **Team view / Client view** previews what the client gets.',
          '**Share**: the **Email** tab (**To**, **Cc**, **Subject**, **Message above the table**, attach the CSV, an "Open the live tracker" button, **Preview**, **Send a test to me**, **Send now** with a confirm), the **Schedule** tab (**Send this update automatically**: every day, every weekday, weekly on chosen days or monthly on a day, **At (Central time)**, **Save schedule**), the **Client link** tab (switch the link on, **Copy link** / **Open**, **Stops working after**, what the page shows, **Make a new link** kills the old one), and **History** (every send: when, how, to whom, how many work orders, sent or failed). **CSV** downloads the list.',
        ] },
        { kind: 'note', title: 'WHAT THE CLIENT SEES', text: 'Only shared columns and charts, the whole tracker (not the viewer\'s scope), read-only, live, with a spreadsheet download. If a banner says email is not switched on for the site, nothing is sent and the attempt is recorded as failed.' },
      ],
    },
    {
      n: 19,
      title: 'Dashboards, Pulse and the Assistant',
      lead: 'What the records say, for the person looking.',
      who: ['Everyone with the Dashboard section', 'Builders: Team Lead, Assistant TL, Account Manager, Admin'],
      where: 'Dashboard; Pulse; the sparkle',
      needs: ['dashboard view / create', 'approvals view (the Awaiting approval card)', 'assistant view'],
      blocks: [
        { kind: 'sub', title: 'Dashboards' },
        { kind: 'steps', items: [
          '**Needs Attention** (No visit logged, Awaiting approval) and **Main Dashboard** (Active WOs, Waiting approval, Ready to invoice, Margin, plus your own Count / Breakdown / Duration cards) are built in. Click **+** at the end of the tabs, name it, **Create dashboard**; it starts private.',
          '**Add card**: what it is called, how it looks (A single number, Bars, A donut, A table, A line over time, A gauge against a target, A live number, A block of text, A picture, A button to a page), **Asked of** (Work orders, Client invoices, Payment requests, Vendor bills, Vendors and technicians, Sites, Assets), what it measures (How many, Total of, Average of, **Time between two moments** with a From and a To moment and Average or Median), **Which work orders?** (Every work order, Open work only, Finished work only), **Cut it by** a field, a target, a tab and a group heading, how wide; **Add card**. The footer says what the card still needs.',
          'The **period** (All time, By month, By quarter, By year, Last 30 days, with Earlier / Later) applies to every card; the **filter bar** (Client, Billing entity, Trade, Store, Dispatcher) narrows the work-order cards.',
          '**Share…**: **Everyone who can open dashboards**, **Roles**, or people one by one ("sharing spreads the question, never the rows"); **Save sharing**. Which dashboards a role opens, and which work orders each counts, is Admin › Roles › Dashboard › Which dashboards.',
          'Click a number to open the list behind it. Every card counts only what the viewer may see.',
        ] },
        { kind: 'sub', title: 'Pulse' },
        { kind: 'p', text: 'Three columns: **Needs me now** (breached and critical), **Due soon** (80 % of the clock gone), **Watching**. Each card is an obligation with its owner and deadline: Ack emergency (2 h), Quote owed (2 business days in Waiting for Quote), ETA owed (2 business hours in Approved), Chase client (5 business days in Waiting for Approval), Quote review (4 business hours, ATL), Payment owed (2 business days in requested, Admin), SLA blown; it clears when the thing it waits for happens. **Snooze** for 1h to 3d with a **Reason**; a critical one can be snoozed only by ATL, TL, AM or Admin. The Pulse lists obligations on every work order, not only your own book.' },
        { kind: 'sub', title: 'The assistant' },
        { kind: 'p', text: 'Click the sparkle, ask in plain words (Enter sends). It looks things up through the same routes you use, so it sees exactly what you see, and it never changes anything. Thumb an answer up or down; an Admin can teach it a note from a marked answer (**Taught**, **Marked answers**). You have 100 questions a day.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 20,
      title: 'Admin Console',
      lead: 'Users, Roles, Settings, Automations, Custom fields, Themes, Audit log, Trash, Vendors & map, Sites & assets, Integrations, Documentation. Each needs its own admin/<section> permission, checked against the person actually signed in.',
      who: ['Admin', 'Super admins'],
      where: 'Admin',
      needs: ['admin/<section> view / edit'],
      blocks: [
        { kind: 'sub', title: 'A. Users' },
        { kind: 'bullets', items: [
          'Invite: **Invite a user**, **Work email**, **Full name**, **Role**, optionally **Super admin**, **Send invitation**. The email must match their Microsoft account exactly; no email is sent — the row is the invitation.',
          'Change a role: the **Role** dropdown in the row (saves at once). **Super admin** switch: nobody changes their own; the last super admin cannot be demoted.',
          '**Disable** (ends sessions at once) / **Re-enable**. **Clients** column: **Assign / Edit** the clients listed on the person (widens "Only theirs" to those clients). **Last sign-in** shows when they were last here.',
          '**Adjust** (super admins only): click cells to set one person\'s permissions on top of their role (faded cells come from the role), **Save adjustments**; **Remove all adjustments** clears them.',
        ] },
        { kind: 'sub', title: 'B. Roles' },
        { kind: 'bullets', items: [
          '**New role**: **Name**, **Description**, optionally **Start from** a copy, set the cells, **Create role**. Open a role, **Find a section or field…**, click a cell under View, Create, Edit, Delete or Approve, **Save role**. An unset cell follows the row above; a write grants View; × returns a cell to inherited.',
          '**Work orders › Which work orders**: Everything or Only theirs; under Only theirs tick **Entity · <Comp>** rows. **Work orders › Status changes**: Change directly, Must request, Not allowed. **Dashboard › Which dashboards**: View per board and **Which work orders it counts**. **Vendors**: Which vendors, Notes and blacklist, Review queue, Documents, Import, Export, Saved lists, Vendor portal, Dispatch offers. **Technician map**: Which technicians, VR vendors, Statewide, Nationwide, Subcontractors, Add a technician, hire. **Admin console**: View / Edit per section.',
          '**Delete** then **Confirm**: not built-in roles, not roles that still have users, and never the only role that can reach the admin console.',
        ] },
        { kind: 'sub', title: 'C. Custom fields and statuses' },
        { kind: 'bullets', items: [
          '**New field**: **Name**, **Type** (Text, Long text, Dropdown, Checkbox, Date, Date & time, $ amount, Number, People, Phone number, Link, Address, Attachment, Function, Rating), **Dropdown values** one per line, **Create … field**. Rename with the pencil; change the type in its row; drag to reorder; edit values under **"<n> values ▾"** (**Save values** / **Reset**). Fields are never deleted.',
          '**Add work order** column: **Not on the form**, **On the form**, **Required**.',
          '**Statuses**: in a phase card, **Add a status to …**, a colour, **Add**; pencil to rename; trash then **Delete status** (only when no work order, trashed ones included, sits at it). **New phase** becomes a list tab; only an empty, non-built-in phase can be deleted.',
          '**Check-in method by FM**: **FM company**, **Method**, **Detail**, **Add**.',
        ] },
        { kind: 'sub', title: 'D. Settings' },
        { kind: 'table', head: ['Card', 'What it sets'], rows: [
          ['Authentication, Server, Database, Contents', 'Read-only: how the instance is configured and how much it holds.'],
          ['Holidays', 'The days the quote clock skips: Day, Name, Add (Rename when the day is on file); remove in the table.'],
          ['Sub-categories', 'Per trade; Rename, Switch off / on. Suggestions for the Sub Category field.'],
          ['Add work order layouts', 'Per client and / or trade: Hidden, Optional or Required per field. The most specific wins; Client and Trade are never hidden.'],
          ['Fault and action codes', 'The code and What it means; Reword; switched off, not deleted.'],
          ['Tax rates', 'Name, %, State, Make default. Nothing on file is recomputed.'],
          ['Document templates', 'Per kind (quote, invoice, purchase order): company name, letterhead, terms, footer; Use it.'],
          ['Approval tiers by amount', 'One table per kind (Payment requests / Vendor bills / Client invoices): From $, Up to $ (blank = no ceiling), Roles, Add band; Remove this band.'],
          ['SharePoint folders', 'Three switches (A folder for each new client / A folder for each new work order / Copy approved files into the work-order folder), the site URL, library and path templates, Test connection, Run now, and the filed-so-far tables. A switch files only records created after it was turned on.'],
          ['Work-order PDFs', 'Per kind (Work order, Request): Title on the document, hide empty fields, Note under the fields, the ordered field list (Add a field, Standard list), Save.'],
        ] },
        { kind: 'sub', title: 'E. Automations' },
        { kind: 'steps', items: [
          '**New automation**, **Name**.',
          '**Trigger**: **A work order is created**, **A field changes** (which field or Any field; optionally "to exactly / to more than / to at least / to less than / to at most" an amount or another field, for money and number fields), or **Manually enrolled**. **Next**. (A wait before acting exists in the API only, up to 30 days.)',
          '**Applies to**: Work orders (Vendors, Quotes and Invoices read Soon). **Next**.',
          '**Conditions**: **+ Add a condition** (field, test, value), AND / OR with brackets. **Next**.',
          '**Actions**: **+ Add an action**: **Set a field** (status, priority or a custom field; empty clears) or **Raise an approval task** (type, optional role). Up to ten.',
          '**Review and turn on** (**Save changes** when editing). Each rule is a card with a switch, its run log (When, Work order, Result: Applied / Skipped / error), edit and delete. Visit-owned and computed fields cannot be set; a rule never triggers itself; Enroll from the bulk bar takes any rule that is on.',
        ] },
        { kind: 'sub', title: 'F. Themes, Audit log, Trash' },
        { kind: 'bullets', items: [
          '**Themes**: click **Blackout** or **Daylight Dispatch** (this browser); the **Current palette** card shows the live colours.',
          '**Audit log**: **From**, **To**, **User**, **Change**, **Search**, **Clear**; **Newer / Older**; **Export CSV**. Nobody can edit or delete a row.',
          '**Trash**: **Restore** a deleted work order. Nothing is removed permanently.',
        ] },
        { kind: 'sub', title: 'G. Vendors & map, Sites & assets' },
        { kind: 'bullets', items: [
          '**Vendors & map**: **The map** (Search radius (miles), Daily alert at, Warn when a vendor\'s COI is missing or expired; **Save**); **Required fields**; **Preferred vendors** (Client and / or Trade, State, City, Vendor, Rank, Note, **Add**); **Suggested vendors** (how many, automatic fill, what an automatic pick must satisfy, paperwork and offers switches, tie-breakers in order); **Dispatch offers** (**Allow dispatch offers**, start by itself, hours to answer); **Vendor invoicing rules** (warn-only, each with its number); the lists (Vendor statuses, Brand sources, Vendor trades, Skills, Consumables: add, rename, turn off); **Map use, last 14 days**.',
          '**Sites & assets**: **Site types** and **Asset categories** (Add a value…, Rename, Switch off / on); **Site access** (super admins only: Restrict another person, pick sites, Lift the restriction; nobody listed = no restriction).',
        ] },
        { kind: 'sub', title: 'H. Integrations' },
        { kind: 'p', text: 'One row per connector (Ecotrak, ServiceChannel, Corrigo, Quo, Outgoing email, Escalation emails, Claude, SharePoint, File storage, Microsoft sign-in) with its mark, what it does, whether it is set up on the server (Connected / On · not set up on the server / Connector not built yet / Off) and one switch. Off makes every button that uses it stop with the reason shown where the button was; keys stay on the server; other servers pick up a flip within 20 seconds. Microsoft sign-in is always on. Each flip is logged.' },
        { kind: 'sub', title: 'I. Documentation' },
        { kind: 'p', text: 'This page: **BRD**, **SOP** and **Lifecycle** tabs; **Print / Save as PDF**, **Download Markdown**, **Download Word** (or **Download SVG** for the chart). The appendix is read from the live instance each time the page opens; the revision history is the migration ledger.' },
      ],
    },
  ],

  successMetric:
    'The One is working when a work order moves from the client\'s system to a paid invoice without a spreadsheet, a Teams reminder or a re-keyed form: the right dispatcher gets it complete, the technician is found in seconds, the quote is out inside 48 business hours, every approval is taken by the right tier in one inbox, the technician is paid from the record, the client sees exactly what was meant for them, and every step can be read back in the audit log.',

  matrix: [
    { role: 'Team Lead / Assistant TL / Account Manager', procedures: [1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19] },
    { role: 'OM (dispatcher) / Senior OM', procedures: [1, 2, 6, 7, 8, 9, 10, 11, 12, 16, 19] },
    { role: 'OM Under Probation / Ops Coordinator', procedures: [1, 2, 6, 7, 8, 10, 11, 12, 19] },
    { role: 'Operations Admin', procedures: [1, 2, 4, 5, 6, 8, 9, 16, 19] },
    { role: 'Accounts Payable', procedures: [1, 2, 10, 12, 19] },
    { role: 'Accounts Receivable', procedures: [1, 2, 13, 19] },
    { role: 'VR Officer', procedures: [1, 2, 15, 19] },
    { role: 'Sales', procedures: [1, 2, 19] },
    { role: 'Admin / Super admins', procedures: [1, 2, 3, 5, 6, 14, 19, 20] },
  ],
};
