// 0075 · The SOP: how the team operates The One, step by step, in the format
// of the Tech Locator Map SOPs (document control, role purpose, scope, who
// can use it, definitions, numbered procedures with notes and tables, success
// metric, revision history drawn from the migration ledger, sign-off).
//
// Every quoted label is the one on screen. WHEN A SCREEN CHANGES, CHANGE ITS
// STEP HERE.

import type { SopDocument } from './types';

export const SOP: SopDocument = {
  title: 'The One — Standard Operating Procedures',
  subtitle: 'Work-order, quote, vendor and payment platform for Seamless FM (Byblos Vista)',
  control:
    'This SOP defines how a work order is received, dispatched, quoted, approved, fulfilled, paid and invoiced in The One, who performs each step, which screen and button does it, and the rules the system enforces along the way. It is generated from the application itself: the procedures are kept beside the code, and the appendix (statuses, fields, roles, automations, integrations) is read from the live instance when this page opens.',
  purpose: [
    'The One is the single system of record for every work order Seamless FM runs on behalf of its clients: it receives the job from the client\'s system or by hand, finds the technician, logs the visits, builds and approves the quote, pays the technician, invoices the client and keeps the client informed, with every action recorded.',
    'Four kinds of people operate it. Managers (Team Lead, Assistant TL, Account Manager, Admin) accept work, approve quotes, payments and status changes, and set the rules. Dispatchers (OM, Senior OM, OM Under Probation, Ops Coordinator) find technicians, run visits and move the job. The Operations Admin drafts work orders typed in by hand and keeps the client systems in step. Accounts (Accounts Payable, Accounts Receivable, VR Officer, Sales) pay, audit, invoice, recruit vendors and watch their clients.',
    'Trust is tiered. A probation dispatcher requests status changes and cannot change the assignee; a senior dispatcher builds quotes; a manager decides. What each role may do is set in Admin › Roles and can be adjusted per person by a super admin.',
  ],
  scope:
    'This SOP covers signing in, the sidebar and top bar, receiving and accepting work orders, drafting them by hand, working the list, running a work order (vendor, visits, status, flags, messages, calls, photos, sign-off), quoting, parts and purchasing, completing the job, paying technicians, auditing and invoicing, the Approvals inbox, vendors and the technician map, sites, assets and clients, planned maintenance, client updates, dashboards and Pulse, the assistant, and every control of the Admin console.',
  whoCanUse:
    'Only people with a row in Admin › Users can sign in, with their Byblos Vista Microsoft account. A byblosvista.com account that is not on file enrols itself as OM Under Probation on first sign-in and is promoted by a super admin; any other address must be invited first. Super admins (Elise, Jordan Brown, Jeff S, Jack) pass every check.',

  terms: [
    { term: 'Work order (WO)', definition: 'One job for one client at one place. Identified by its WO # (the client\'s number when it came from their system).' },
    { term: 'Client CMMS', definition: 'The client\'s own maintenance system (Ecotrak, Corrigo, ServiceChannel). Work orders come from it; approved quotes and status changes go back to it once the connector is live. Which one a work order came from is the Client Portal Type field.' },
    { term: 'Dispatcher', definition: 'An OM, Senior OM, OM Under Probation or Ops Coordinator: the person assigned to run the work order (the Assignee).' },
    { term: 'Technician / vendor', definition: 'An external subcontractor who does the work. A VR vendor is a company the Vendor Relations team recruited; a technician is someone a dispatcher has worked with. Both are vendor records.' },
    { term: 'Status and phase', definition: 'The status is where the work order sits (Open, Assessment Sched, Waiting for Quote, …); statuses are grouped in phases (Open, Active, Pending, Done, Closed) that are the list\'s tabs. Admin edits both.' },
    { term: 'Gate', definition: 'A rule that refuses a status until the record is ready: Quote Ready needs a quote, the parts statuses need Parts Required, Done / Incurred needs a completed visit, the Cost, a quote and an approved after photo.' },
    { term: 'Request mode', definition: 'A role that cannot change a status directly picks one and a request goes to a manager in Approvals.' },
    { term: 'NTE', definition: 'Not-to-exceed: the client\'s ceiling for the job. Cost above it raises an NTE override task that holds the quote and the payment until a manager decides.' },
    { term: 'Visit (CICO)', definition: 'One technician visit with its check-in and check-out stamps: Assessment, Job or Return trip. A check-in moves the work order On Site.' },
    { term: 'Quote clock', definition: 'Quote Due Date: 48 business hours after the assessment check-out, skipping weekends and the holiday table, Chicago time.' },
    { term: 'Yoda', definition: 'The payment tool Accounts Payable hands approved technician payments to (Send to Yoda).' },
    { term: 'Scope ("Only theirs")', definition: 'A role or person who sees only the work orders assigned to them, widened by billing entities, assigned clients, or narrowed to a list of sites.' },
    { term: 'Super admin', definition: 'One of the four named people who pass every permission check and alone can adjust one person\'s permissions.' },
    { term: 'Audit log', definition: 'The append-only record of every change (who, when, before, after). Nothing in it can be edited or deleted.' },
  ],

  procedures: [
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 1,
      title: 'Signing In',
      lead: 'Access is Microsoft sign-in only; The One holds no passwords.',
      who: ['Everyone'],
      where: 'The sign-in page',
      needs: [],
      blocks: [
        { kind: 'steps', items: ['Open the site and click **Sign in with Microsoft**.', 'Use your Byblos Vista Microsoft account; any other account is rejected unless it has been invited in Admin › Users.', 'You land on the page you asked for, or on Work Orders (Dashboard for a role with no work orders).'] },
        { kind: 'note', title: 'NOTE', text: 'A session is a row on the server. Sign out from the account menu to end it; a disabled account loses its sessions immediately. A permission change takes effect on the next request, not the next sign-in.' },
        { kind: 'note', title: 'FIRST SIGN-IN', text: 'A byblosvista.com account that is not on file is created as OM Under Probation and logged. Ask a super admin to set your role in Admin › Users.' },
      ],
    },
    {
      n: 2,
      title: 'Finding Your Way',
      lead: 'One frame around every screen: the sidebar is your job, the top bar is your tools.',
      who: ['Everyone'],
      where: 'Every page',
      needs: [],
      blocks: [
        { kind: 'bullets', items: [
          '**Sidebar**: Dashboard, Pulse, Work Orders, Vendors, Sites, Assets, Clients, Quotes, Payments, Incoming Work Orders, Planned Maintenance, Maintenance, Approvals, Receivables, Contracts, Purchasing, Client Updates, Admin. You only see the items your role includes. Badges: Work Orders (what you may see), Approvals (what waits on you), Incoming Work Orders (to accept plus open drafts).',
          '**Search** (top bar): type a WO number, client, store or words from the description; pick a result to open it.',
          '**Bell**: obligations that are due (Pulse) and notices for you (a task given to you, a review to make, a decision on your request, an insurance date expiring).',
          '**Sparkle**: the assistant. Ask a question about the data ("which of my work orders are waiting for parts?") or about the app ("how do I request a status change?"). It answers only from what you may see and never changes anything.',
          '**Sun / moon**: switch between the Blackout and Daylight Dispatch themes for this browser.',
          '**Account menu**: Sign out. Super admins also find View as here.',
        ] },
        { kind: 'note', title: 'LOCKED WITH A REASON', text: 'A page or button you may not use is shown locked with a sentence saying why and who to ask. Nothing fails silently.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 3,
      title: 'Receiving and Accepting Work Orders',
      lead: 'Every work order that arrives without a dispatcher waits on Incoming Work Orders until a manager accepts it and names one, or rejects it.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Incoming Work Orders › To accept',
      needs: ['approvals/intake view', 'approvals/intake approve'],
      blocks: [
        { kind: 'p', text: 'Work orders arrive from the Ecotrak sync (manual trigger, Admin › Integrations), from the CSV import on the Work Orders list, from a planned-maintenance schedule (already assigned, skips this queue), from an OP Admin draft (already assigned, skips this queue) or from the Add work order form.' },
        { kind: 'sub', title: 'Accept and assign' },
        { kind: 'steps', items: [
          'Open **Incoming Work Orders**. Rows are oldest first; each shows the client, store, trade, due date and where it came from.',
          'If the row says **Fill before assigning: …**, open the work order (the link on the row) and fill the listed fields on **All fields**. The 13 intake fields are Received on, Due date, SLA, Address, City, State, Zip code, Store, Trade, WO description, FM, Comp and Client NTE ($0.00 counts as filled).',
          'Click **Accept**. Under **Assign to**, pick the dispatcher. Click **Who\'s available?** to see the people listed on this client (or **All dispatchers**) with the number of active work orders each holds; **Fewest first / Most first** flips the order; the chevron shows their work orders per status; clicking a name picks them.',
          'Click **Accept and assign**. The work order is assigned as your own edit (audited), appears in that dispatcher\'s list, and a sign-off sheet is generated for it.',
        ] },
        { kind: 'sub', title: 'Reject' },
        { kind: 'steps', items: ['Click **Reject**, type the reason, click **Reject with note**.', 'The work order moves to Cancelled / Postponed and leaves the queue.'] },
        { kind: 'note', title: 'RULES', text: 'Accept stays locked while an intake field is missing (rule 11.1.1). Filling the Assignee by hand on the work order, or cancelling it, closes the acceptance by itself. Dispatcher tiers cannot change the Assignee (rule 8.5.4); a manager can, from the People tab.' },
      ],
    },
    {
      n: 4,
      title: 'Drafting a Work Order by Hand (WO Intake)',
      lead: 'The Operations Admin\'s staging area for jobs that come by email or phone.',
      who: ['Operations Admin', 'Admin'],
      where: 'Incoming Work Orders › Drafts',
      needs: ['intake view', 'intake create', 'intake edit'],
      blocks: [
        { kind: 'steps', items: [
          'On **Drafts** click **New work order**.',
          'Type the **WO #** (the client\'s number) and fill the fields; they are the same 13 intake fields plus Client and the **Assignee** (use **Who\'s available?**).',
          'Click **Save draft** to keep it; the row shows what is still missing.',
          'When it reads **Ready to submit**, click **Submit & assign**. The work order is created in status Open, already assigned, and the draft is marked submitted. No acceptance is raised: your assignment is the handoff.',
          'To drop a draft: **Discard**, then **Yes, discard**. The row is kept as discarded.',
        ] },
        { kind: 'note', title: 'RULES', text: 'Submit refuses a WO # that already exists (even in Trash) and refuses while a required field or an active assignee is missing.' },
      ],
    },
    {
      n: 5,
      title: 'Adding a Work Order from the List',
      lead: 'The same act without the draft, for anyone with the create right.',
      who: ['Operations Admin', 'Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Work Orders › Add work order',
      needs: ['work_orders create'],
      blocks: [
        { kind: 'steps', items: [
          'Click **Add work order**. Optionally **Start from a template…**.',
          'Type the **WO #**. A number in use is refused as you type.',
          'Optionally pick a **Site** and an **Asset**; the site fills the client, store and address while those fields are empty.',
          'Fill the sections. Fields marked * are required; the footer lists what the form **Still needs**. Which fields appear and which are required is set in Admin › Custom fields (Add work order column) and Admin › Settings (layouts per client or trade).',
          'Optionally add files under **Photos and files**; they upload once the work order exists and wait for approval like any upload.',
          'Click **Create work order**. **Save template** keeps the filled form (My templates; Share it with everyone needs admin/fields edit).',
        ] },
        { kind: 'note', title: 'DUPLICATES', text: 'The WO # is identity and is refused when taken. "Possible duplicates" (same store and trade still open, open work on the same asset or site) is a warning with links, never a block: a store really can break twice.' },
        { kind: 'note', title: 'IMPORT', text: 'To load many at once: **Import**, **Choose file**, match each column under **Match the columns**, choose **Create and update** or **Only create**, **Preview**, **Import N rows**. A row whose WO # exists updates that work order. Imported rows without an assignee go to the acceptance queue.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 6,
      title: 'Working the Work Orders List',
      lead: 'Arrange the list for your job once; it remembers.',
      who: ['Everyone with work orders'],
      where: 'Work Orders',
      needs: ['work_orders view', 'work_orders/export view for Export'],
      blocks: [
        { kind: 'bullets', items: [
          '**Tabs** along the top are views: All work orders, Due Today, Escalation Tracker, then saved views. Click a row or its WO number to open it.',
          '**Segments** (All, Open, Active, Pending, Done, Closed, …) filter by phase.',
          '**Chips** Status, Assignee, FM, Comp, AM: tick values; **Clear** removes them.',
          '**Filter › Add filter**: any field, a test, a value; **Match all / Match any**. **Group**: by any field, counts per bucket; **No grouping** undoes it. Click a column header to sort; **Sort by breach** puts the nearest deadline first. **Columns**: reorder or remove under **Shown**, add under **Add a column**.',
          '**Save view**: name it, tick **Share with the team** if everyone should have it, **Save**. The pencil and trash icon are the owner\'s; the pushpin makes it your landing view.',
          '**Export**: a CSV of the filtered rows in the shown columns (logged).',
          '**Status pill** in a row: change (or request) the status without opening the work order; the same gates apply.',
        ] },
        { kind: 'sub', title: 'Due Today (the daily to-do)' },
        { kind: 'table', head: ['Segment', 'What it lists for the picked day'], rows: [
          ['All', 'Everything the other four list.'],
          ['Escalations', 'Due Date on or before the day and not yet scheduled or on site (Job Sched, On Site (Job) are exempt).'],
          ['Scheduled', 'Scheduled Date on the day.'],
          ['Quote', 'Quote Due Date on the day, plus overdue quotes while the status is still before Quote Ready (today only).'],
          ['Parts arriving', 'Parts Arrival Date on the day.'],
        ] },
        { kind: 'p', text: 'Pick **Today**, **Tomorrow** or a date. The Filter menu is hidden here; the chips still work.' },
        { kind: 'sub', title: 'Bulk actions' },
        { kind: 'steps', items: [
          'Tick rows, the header box (this page) or **Select all N matching**.',
          '**Edit**: **Add a field**, set the value (blank clears), **Apply to selection**. Visit-owned fields, Quote Due Date, and a Cost or Total Invoiced the system has written are refused.',
          '**Set status**: picks a status for the whole selection (hidden for request-mode roles). If any row would fail a gate, the whole move is refused and the message names the work orders.',
          '**Enroll**: puts the selection through an automation that is marked Manually enrolled.',
          '**Delete**, then **Move to Trash**: restorable from Admin › Trash.',
        ] },
        { kind: 'note', title: 'SCOPE', text: 'A person limited to their own work orders sees a "Yours only" or "Yours + <Comp>" chip; a work order outside their scope answers "is not assigned to you", and a bulk selection must be wholly inside it.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 7,
      title: 'Running a Work Order: Vendor, Visits and Status',
      lead: 'The dispatcher\'s core loop: find the technician, log the visits, move the status.',
      who: ['OM (dispatcher)', 'Senior OM', 'OM Under Probation', 'Ops Coordinator'],
      where: 'The work-order page: header, action bar, People and CICO tabs',
      needs: ['work_orders edit', 'work_orders/fields/cico edit', 'vendor_map view / create', 'work_orders/status edit or create'],
      blocks: [
        { kind: 'sub', title: 'A. Find and hire the technician' },
        { kind: 'steps', items: [
          'Open the **People** tab. The **Suggested vendors** card lists the top vendors for this work order: the hand-picked preferred vendors for the client / trade / state / city first, then the best fit by trade, coverage, client history, distance, compliance, jobs and rate. Blacklisted vendors never appear.',
          'Or click **Find a technician** on the **Technicians** card to open the map centred on the work order (radius set by Admin). Filter by **Trade**, **Availability** (Emergency same day, After hours, Weekends, Holiday emergency) and **Show** (VR vendors, your technicians, statewide, nationwide, as your role allows). Pin shape is the source; pin colour is the trade.',
          'Click a pin for the card: phones (tap to call), rates, trip charge, response time, coverage, compliance. Click **Hire for <WO#>**. A missing or expired COI warns; it never blocks. The technician is recorded on the work order and joins your own technician list.',
          'To phone: **Call** in the header, pick **Who**, choose **Just call** or **Call and draft a quote**, click **Call via Quo**. The Quo desktop app dials; the call, transcript and summary come back to the **Calls** card on the Messages tab.',
          'Optionally **Assign vendor** on the action bar names the one responsible vendor for the record (a blacklisted vendor is refused).',
        ] },
        { kind: 'sub', title: 'B. Log the visits (CICO)' },
        { kind: 'steps', items: [
          'On the **CICO** tab click **New visit**.',
          'Pick the **Visit type** (Assessment, Job or Return trip), the **Technician** (free text, or anyone on file: hired first), the **Phone** and the **Method** (pre-filled from the FM). Click **Log visit**.',
          'When the technician arrives, set the row\'s status to **Checked in**. The time is stamped and the work order moves by itself to **On Site (Assessment)** or **On Site (Job)** (rule 2.2.2). Optionally record the location: **Use this device\'s location** or **Type coordinates**; the result is checked against the site\'s pin.',
          'When they leave, set **Checked out** (or **Checked out · return trip needed**). An Assessment check-out stamps **Quote Due Date** (48 business hours). A Job check-out never does.',
          'Correct a stamp with the pencil (**Save visit**); delete with the trash icon.',
        ] },
        { kind: 'note', title: 'SIGN-OFF SHEET', text: 'The sheet was generated when the work order was assigned (the panel at the foot of the CICO card). Click **Share with tech**, pick the technician\'s number (or type one) and send; the link is texted through Quo. When the signed copy is texted back it is filed as a pending Sign-off attachment and Sign-Off Link is set. If several sheets could match, each candidate shows **Yes, file it here / Not this one**. **New sheet** regenerates after a number or address change.' },
        { kind: 'sub', title: 'C. Move the status' },
        { kind: 'steps', items: [
          'Click **Change status** in the header (or the status pill in the list) and pick the next status. Roles in request mode see **Request status change** instead: the pick raises a request a manager decides in Approvals, and the decision shows on the header chip (click **Continue** or **Understood** to clear it; **Request again** or **Withdraw** are in Approvals › My requests).',
          'A pick the record is not ready for is tagged and refused with the reason:',
        ] },
        { kind: 'table', head: ['Status', 'Needs', 'Tag in the menu'], rows: [
          ['Quote Ready', 'A quote with at least one line item or scope line.', 'Needs quote'],
          ['Waiting for Parts, Please Order Parts', 'The Parts Required field written (Parts tab).', 'Needs parts'],
          ['Done / Incurred', 'A visit checked in and out; Cost; a quote with data; an approved After photo (Bill For Incurred: an approved Before photo and Sign-off).', 'Needs check-out / Needs cost / Needs quote / Needs after photo; Not ready for several'],
          ['Any', 'A move Ecotrak would refuse from the work order\'s Ecotrak status.', 'Ecotrak (a warning, unless the site is set to block)'],
        ] },
        { kind: 'sub', title: 'D. The action bar' },
        { kind: 'bullets', items: [
          '**Pause** (reason) / **Resume**: a marker on the record; no clock stops (rule 2.4.4).',
          '**Add ETA**: **Expected on site**, **Save ETA**; **Clear the ETA**.',
          '**Tag**: a **Tag** and a **Reason**, **Add the tag**.',
          '**Increase NTE**: **New NTE** and **Why more is needed**, **Send the request**. A manager decides it on the **Cost breakdown** tab; approval writes the NTE.',
          '**Complete service**: **Completion note**, fault code, action code, temporary fix; records the completion and does not move the status.',
          '**Cancel work order** (reason) / **Reopen**.',
          '**Save as PDF**: **Work order** or **Request**, in the billing entity\'s branding.',
        ] },
      ],
    },
    {
      n: 8,
      title: 'Flags, Messages, Photos and Files',
      lead: 'What everyone else sees about the job.',
      who: ['Dispatchers', 'Managers', 'Operations Admin'],
      where: 'Header, Flags tab, Messages tab, Overview › Photos',
      needs: ['work_orders/comments create', 'work_orders/comments/client create', 'work_orders/attachments create / approve'],
      blocks: [
        { kind: 'sub', title: 'Flags' },
        { kind: 'bullets', items: [
          '**Emergency**: the checkbox on the Flags tab (or All fields). Turns the work order red in every list, queue and board.',
          '**Mark as Escalated** in the header (managers; dispatcher tiers see the field read-only). Turns it amber, pins it at the top of the Approvals inbox and lists it on the Escalation Tracker tab. **Escalated · Clear** removes it. An email tool can set it through the escalation webhook.',
        ] },
        { kind: 'sub', title: 'Messages' },
        { kind: 'steps', items: [
          'On the **Messages** tab choose **Internal** (the team) or **Client-visible** (what the client\'s system will receive).',
          'Type and click **Post internally** or **Send to client**. A client-visible message queues for the client\'s CMMS and the bubble says when it will be sent.',
          'Edit your own message with the pencil only until it is sent; a sent message cannot be changed. A note the client wrote in their system is never editable.',
        ] },
        { kind: 'sub', title: 'Photos and files' },
        { kind: 'steps', items: [
          'In the message box click the camera (**Add photo**) or **Attach file**. Photos are shrunk in the browser first; the cap is 4 MB.',
          'Every upload waits for approval. On **Overview › Photos › Waiting for approval**, a reviewer picks **What is it?** (Before photo, After photo, Sign-off, Other), optionally renames, then **Approve** or **Decline**. Until then only reviewers and the uploader can see it.',
          'Approved photos group by kind and, when the SharePoint switch is on, are copied into the work order\'s SharePoint folder.',
        ] },
        { kind: 'note', title: 'WHY', text: 'Done / Incurred needs an approved After photo (or Before photo plus Sign-off for Bill For Incurred): rules 1.3.1 to 1.3.4 and 11.3.4. The "Needs after photo" tag clears the moment one is approved.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 9,
      title: 'Quoting',
      lead: 'One quote per work order, due 48 business hours after the assessment, priced from the client contract.',
      who: ['Senior OM', 'Team Lead', 'Assistant TL', 'Account Manager'],
      where: 'The Client quote card › the quote builder; Quotes',
      needs: ['quotes create', 'quotes edit', 'quotes approve'],
      blocks: [
        { kind: 'steps', items: [
          'On the work order\'s **Finances** tab, **Client quote** card, click **Create quote**, then **Create quote** again in the builder. The number (Q-<entity>-<year>-<n>) is issued and the client contract\'s rates are snapshotted.',
          'Fill **Tech reported that…** (required). **Add line** for priced items (quantity, rate, unit, tax %, markup %, overtime); **Add scope line** for the scope; **Add option** for alternatives (tick include in summary for those that bill). Pick a tax rate with the picker if sales tax applies. It saves as you type.',
          'Fix anything the red chip lists, then click **Submit for approval**. The quote appears in Quotes › Pending approval and in Approvals › Quotes.',
          'A manager clicks **Approve & Send to CMMS** in the builder (or **Approve & send** on the Quotes list, or **Approve** in Approvals, which approves only), or **Reject with note** / **Decline** (a note is required; the quote returns to draft).',
          'Move the status to **Quote Ready**, then **Waiting for Approval** once it is with the client. **Print / PDF** prints the quote with the default template\'s letterhead and terms.',
        ] },
        { kind: 'note', title: 'AI DRAFT', text: 'From a call placed with **Call and draft a quote** that has a transcript, click **Draft a quote with AI** on the Calls card. The draft opens in the builder\'s own editors beside the transcript with its assumptions and missing information; adjust it and click **Submit quote**. Prices are never invented: the client price stated, the vendor cost plus the contract markup, the contract rate, or a listed gap at $0.' },
        { kind: 'note', title: 'HOLD', text: 'Approving and sending are locked while an NTE override task is open on the work order ("On hold — decide the NTE override under Approvals first"). Rejecting is never locked. Once approved, the quote is never re-priced.' },
      ],
    },
    {
      n: 10,
      title: 'Parts and Purchasing',
      lead: 'Parts are written on the work order before a parts status; bigger buys go through purchasing.',
      who: ['Dispatchers', 'Accounts Payable', 'Team Lead'],
      where: 'The Parts tab; Purchasing',
      needs: ['work_orders edit', 'purchasing/requests, rfqs, orders, budgets'],
      blocks: [
        { kind: 'steps', items: [
          'On the **Parts** tab write **Parts Required** (what, how many, where from) and the **Parts Arrival Date** when known.',
          'Move the status to **Please Order Parts** (AP orders) or **Waiting for Parts** (ordered). Both are refused while Parts Required is empty (rule 11.2.2). Due Today lists the arrival under **Parts arriving**.',
          'When parts arrive, schedule the job (**Job Sched**) and log the Job visit.',
        ] },
        { kind: 'sub', title: 'Purchasing (Purchasing in the sidebar)' },
        { kind: 'bullets', items: [
          '**Requests**: **New request**, what is being bought, items (**+ Add a line**), optionally the work order; **Save as draft** or **Submit for approval**. A manager opens it and clicks **Approve**, or writes a **Note to the requester** and **Reject**. From an approved request: **Ask vendors for quotes** or **Raise a purchase order**.',
          '**Requests for quotation**: items and vendors; **Mark as sent to vendors** (recorded, nothing is emailed); **Record quote** per vendor; **Award** drafts the purchase order from the winner.',
          '**Purchase orders**: **Issue the order** (needs approve); when goods arrive enter quantities and **Save what arrived**; **Close the order**; **Print / PDF**.',
          '**Budgets**: cost centers and AFEs; going over warns on the order and never blocks.',
        ] },
        { kind: 'note', title: 'RULE', text: 'A purchase order never changes a work order\'s Cost. Cost is the technician payments (SOP 12).' },
      ],
    },
    {
      n: 11,
      title: 'Completing the Job',
      lead: 'Done / Incurred is the soft close: the system checks the proof before it accepts it.',
      who: ['Dispatchers', 'Managers'],
      where: 'The work-order page',
      needs: ['work_orders/status edit or create'],
      blocks: [
        { kind: 'steps', items: [
          'Make sure the Job visit is **Checked out** on the CICO tab (rule 11.3.1).',
          'Make sure the **After photo** is uploaded and approved (SOP 8). For a Bill For Incurred job, a Before photo and the Sign-off instead (rule 11.3.4).',
          'Make sure the technician\'s payment request has been approved (SOP 12): **Cost** is the total of accepted requests and cannot be typed once the system has written it. A work order with no payment request still takes a typed Cost (rule 11.3.2).',
          'Make sure the quote has data (rule 11.3.3).',
          'Optionally **Complete service** on the action bar: completion note, fault code, action code.',
          'Change the status to **Done / Incurred**. If a contract covering this work order has **Bill automatically on completion**, a proposed invoice (and a proposed vendor bill) appears for Accounts to confirm.',
        ] },
        { kind: 'note', title: 'RETURN TRIPS', text: 'If the job is not finished, check out as **Checked out · return trip needed** and move to **Return Trip Needed**; the next check-in moves it back On Site (Job).' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 12,
      title: 'Paying the Technician',
      lead: 'A request per payment, approved by the right tier, handed to Yoda, marked paid.',
      who: ['Dispatchers (request)', 'Team Lead / Assistant TL / Account Manager (approve)', 'Accounts Payable (process)'],
      where: 'The Payables tab; Payments',
      needs: ['payments create', 'payments approve', 'payments/process edit'],
      blocks: [
        { kind: 'steps', items: [
          'On the work order\'s **Payables** tab, **Payment requests** card, click **Request payment**. Pick the **Vendor record**, fill **Purpose**, **Amount** and **Method**, click **Submit payment request**.',
          'An approver opens **Payments › Needs approval** and clicks **Approve** then **Approve payment**, or **Reject**, gives the reason and clicks **Reject with note**. The button is locked with the reason when the amount is outside the approver\'s tier (Admin › Settings › Approval tiers) or while an NTE override is open.',
          'Accounts Payable opens **Payments › To process**, clicks **Send to Yoda** (optional **Yoda reference**) and later **Mark paid**.',
        ] },
        { kind: 'table', head: ['Rule', 'What happens'], rows: [
          ['Cost follows the payments', 'Cost = the sum of accepted requests (approved, sent to Yoda or paid); rejecting one takes it back out.'],
          ['NTE override (1.5.2)', 'When Cost passes the client NTE an NTE override task lands in Approvals and holds Send to Yoda and the quote; it cancels itself once Cost is back under the NTE.'],
          ['Tiers (6.2.3)', 'Under $500 anyone with the permission; $500 to $3,000 TL / ATL / AM / Admin; over $3,000 TL / Admin (as seeded; Admin › Settings edits the bands).'],
        ] },
        { kind: 'sub', title: 'Vendor bills' },
        { kind: 'steps', items: [
          '**Payments › Vendor bills › Record bill**: the work order, **Vendor**, **Their invoice #**, dates and lines; **Record bill**.',
          '**Approve** (payments approve), **Mark paid** (payments/process edit), or **Dispute** with what is wrong (back to received on resolve). **Credit note** raises a credit against it. A bill that trips an invoicing rule shows a warning; it is never blocked.',
        ] },
      ],
    },
    {
      n: 13,
      title: 'Auditing and Invoicing the Client',
      lead: 'A pristine record first, then one invoice per work order from the approved quote.',
      who: ['Accounts Receivable', 'Admin'],
      where: 'Receivables › Audit and Invoicing',
      needs: ['invoicing view', 'invoicing create', 'invoicing edit', 'invoicing approve'],
      blocks: [
        { kind: 'sub', title: 'Audit' },
        { kind: 'steps', items: [
          'Open **Receivables › Audit**. Lanes **All · Clean · Minor · Major** show the auto-check results per completed work order.',
          'Fix what the checks flag on the work order, resolve grey flags (**Resolve via**), then tick **Admin** and **Quote**. A clean, ticked work order becomes **Ready** on the Invoicing tab; move its status to **Ready to Invoice**.',
        ] },
        { kind: 'sub', title: 'Invoicing' },
        { kind: 'steps', items: [
          'On **Invoicing › Ready** click **Raise invoice**. The draft is built from the approved quote (incurred plus the options flagged for the summary, overtime folded in) or, with no quote and a T&M contract, from hours on site plus the trip charge. Edit the lines while it is a draft.',
          'Click **Send** (needs approve; the amount tier applies; a zero total cannot be sent). The number (<entity>-<year>-<n>) is fixed and the lines are frozen. Move the status to **Invoiced Not Paid**: Total Invoiced is stamped from the quote.',
          'When the client pays, click **Mark paid** and move the status to **Invoiced**. **Void** keeps the number and can be reopened.',
          '**Proposed**: when a contract has **Bill automatically on completion**, completion drafts a proposal; **Confirm** files the invoice with exactly those lines, **Dismiss** drops it.',
          'Print at the invoice\'s **Print / PDF** with the default template.',
        ] },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 14,
      title: 'The Approvals Inbox',
      lead: 'Every yes-or-no the system needs from a manager, in one place, oldest first.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Approvals',
      needs: ['approvals view', 'approvals/nte, status, reviews approve', 'quotes approve', 'payments approve'],
      blocks: [
        { kind: 'table', head: ['Section', 'What waits there', 'Deciding it does'], rows: [
          ['NTE increases', 'NTE override tasks raised when Cost passes the NTE; manual Increase NTE requests on the Cost breakdown tab.', 'Approve releases the quote and the payment (and writes the new NTE for a manual request); Reject keeps the hold.'],
          ['Status changes', 'Requests from request-mode roles, with from → to and an Ecotrak tag when Ecotrak would refuse.', 'Approve moves the work order; Reject (reason) sends it back.'],
          ['Manager reviews', 'Review tasks raised by automations.', 'Approve / Reject with a note.'],
          ['Quotes', 'Quotes pending approval.', 'Approve (approves only; sending is from the builder) / Reject with note.'],
          ['Payments', 'Payment requests in requested.', 'Approve payment / Reject with note.'],
        ] },
        { kind: 'bullets', items: [
          'Lanes: **For me**, **Open**, **Done**, **My requests**. Escalated rows pin to the top. Open rows are oldest first and every decision is per row.',
          '**Claim** takes a task for yourself. **Approve** takes an optional **Note**; **Reject** needs the reason, then **Reject with note**.',
          'Under **My requests**: **Withdraw** a request still open; after a decision **Continue** (approved) or **Understood** (rejected) clears it from the header chip.',
          'Acceptances are not here: they have their own page, Incoming Work Orders (SOP 3).',
        ] },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 15,
      title: 'Vendors and Technicians (Vendor Relations)',
      lead: 'The One\'s own vendor network: records, documents, compliance, tasks, alerts and the coverage map.',
      who: ['VR Officer', 'Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      where: 'Vendors (List, Board, Tasks, Alerts, Data quality, Performance, Coverage map)',
      needs: ['vendors view / create / edit / delete', 'vendors/documents create', 'vendors/review approve', 'vendors/blacklist', 'vendors/lists', 'vendors/import create', 'vendors/export view'],
      blocks: [
        { kind: 'sub', title: 'Add and maintain a record' },
        { kind: 'steps', items: [
          'Click **Add vendor**. Fill **Name** (required), **Kind** (VR vendor or Technician), **Primary trade**, **City**, **State** and phones; **Add vendor**. "This may already be on file." warns of a likely duplicate (same name or phone); "Still needed:" lists the required fields (Admin › Vendors & map). A VR vendor saved without one is flagged and opens a review task.',
          'Open the vendor, **Edit**, fill rates, availability, coverage (radius, whole state, nationwide), payment terms, contacts; **Save changes**. The record is placed on the map from its ZIP or city.',
          '**Documents**: pick the type (W-9, MSA, COI, other) and **Upload**. A COI opens a compliance review: a reviewer ticks the six checks and approves or sends it back; **Insurance dates** are added on their card. Compliance is derived: APPROVED when W-9, MSA and an approved COI are in; EXPIRED when an insurance date passed. A New / Interested / Ready vendor turns Active when approved.',
          '**Notes**: type a note; to blacklist, tick **Blacklist with this as the reason** and click **Mark blacklisted** (visible to all, sorts last, never suggested, cannot be assigned). **Clear blacklist** needs the edit right.',
          'Log calls and emails on the record; a call\'s outcome may set the status.',
        ] },
        { kind: 'sub', title: 'Work the queues' },
        { kind: 'bullets', items: [
          '**Tasks**: duplicate, missing-info and compliance reviews in one queue (decide with the review right); compliance fixes and manual tasks assigned to a person; daily targets for nationwide / statewide vendors added.',
          '**Alerts**: every insurance date that counts, banded by how soon it expires. **Data quality**: duplicates by name or phone, records missing required fields, records not on the map.',
          '**Board**: records by status; drag a card or **Move to…**. **Performance**: jobs, SLA met / missed, recalls, offers taken, billed.',
          '**List tools**: advanced filters (AND / OR), **Columns**, **Save as a list** (Name, Who sees it), bulk edit of one field, **Export CSV**, **Look up a list** (paste names / phones / emails).',
          '**Import**: choose the kind and a CSV, map the columns, **Check the file**, choose how to treat duplicates (skip, skip and report, add flagged, fill in the record on file), **Import N rows**. Bad cells are reported and left empty.',
          '**Coverage map**: every placed vendor, for "where do we recruit next".',
        ] },
        { kind: 'note', title: 'VENDOR PORTAL', text: 'On a vendor, create a portal link (shown once). The vendor sees its jobs in a fixed shape with no money or internal notes and can fill an onboarding form that waits for one of us to accept. No email is sent: copy the link to them.' },
        { kind: 'note', title: 'DISPATCH CASCADE', text: 'Off by default. When Admin turns it on, a new work order with no vendor is offered to the preferred vendors of its client / trade / state in turn; each offer has a clock; accepting sets the responsible vendor. Preferred vendors are rules in Admin › Vendors & map.' },
      ],
    },
    {
      n: 16,
      title: 'Sites, Assets and Clients',
      lead: 'The places, the equipment and the accounts.',
      who: ['Dispatchers', 'Operations Admin', 'Managers', 'Admin'],
      where: 'Sites, Assets, Clients; the Site card of a work order',
      needs: ['sites', 'assets', 'assets/requests', 'clients'],
      blocks: [
        { kind: 'bullets', items: [
          '**Site**: **Add site** (Client, Store number, address), **Edit**, add a **Building** or **Space**, **Add asset**, add a site event (closure, restricted access, remodel; shown as a chip on the site\'s work orders while running). On a site that came from Ecotrak the name, client, store number and address are locked. **Sites from work orders** previews and creates a site per place found in the history.',
          '**Asset**: **Add asset** (Site, Name, Category), **Edit**, **Record a reading** for its condition; warranty state is shown. People without the edit right use **Request a change** (add, replace, retire, move, with a reason); a manager decides under **Assets › Requests**, and approving makes the change.',
          '**Client**: **Add client** (Name, Code, Account manager, Payment terms), **Edit**, make inactive. A client with work orders or sites cannot be removed. The spelling here names the SharePoint folder.',
          '**On a work order**: the **Site** tab\'s **Site record** block links a site and an asset; the address fields stay the work order\'s own text.',
        ] },
        { kind: 'note', title: 'SCOPE', text: 'Every work-order list inside a site or an asset follows the viewer\'s work-order scope. A person restricted to a list of sites (Admin › Sites & assets) sees only those sites, their assets and their work orders.' },
      ],
    },
    {
      n: 17,
      title: 'Planned Maintenance and the Maintenance Tabs',
      lead: 'Recurring jobs that raise their own work orders, and the plans, services, time and permits around them.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin', 'Dispatchers (view)'],
      where: 'Planned Maintenance; Maintenance',
      needs: ['planned_maintenance create / edit / delete', 'maintenance/assignment, job_plans, services, time, permits'],
      blocks: [
        { kind: 'steps', items: [
          '**Planned Maintenance › New schedule**: **What is the job?**, **How often** (every n days / weeks / months / years), **First due on**, the client, store, trade, NTE, **Assignee**, optional **Job plan** (its steps become the checklist), lead days; **Create schedule**.',
          'The schedule raises one work order per due date inside the lead window, as **PM Sched**, already assigned, with WO # <code>-<date>. It runs when the list opens, after saving, on **Raise now**, and daily by the server\'s cron. **Skip** records a skipped occurrence; **Delete schedule** keeps its work orders.',
        ] },
        { kind: 'bullets', items: [
          '**Maintenance › Assignment**: pick **Unassigned**, **Everything open** or a person, tick work orders, choose in **Assign to…**, **Assign**.',
          '**Job plans**: **New job plan**, Name, Steps one per line, **Add job plan**; applied from a work order\'s Checklist tab or by a schedule.',
          '**Services**: **New service**, Name, Unit, Price per unit, Cost per unit. Services never feed Cost.',
          '**Time tracker**: time entries logged on a work order\'s Timelog tab (a running timer when no end). **Work permits**: written on a work order\'s Related tab (PTW-n: draft → requested → approved → closed, or rejected) and decided by someone with the approve right.',
        ] },
      ],
    },
    {
      n: 18,
      title: 'Keeping the Client Informed (Client Updates)',
      lead: 'A live tracker per client, shared by link, email or schedule, instead of a spreadsheet.',
      who: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin', 'Dispatchers (view)'],
      where: 'Client Updates; /share/client-updates/<token> for the client',
      needs: ['client_updates create / edit', 'client_updates/share edit'],
      blocks: [
        { kind: 'steps', items: [
          '**New tracker**: **Client**, **Tracker name**; adjust the filter, columns (**Add column**, each **Client sees it** or **Team only**), charts (**Add chart**), sections and the note column; **Create tracker**.',
          'Type client-facing notes straight into the note column of a row (it writes the work order\'s field, audited).',
          '**Share**: the **Client link** tab (switch the link on, **Copy link**; **Make a new link** kills the old one; optional expiry), the **Email** tab (**To**, **Subject**, **Send a test to me**, **Send now**, optional CSV), the **Schedule** tab (**Send this update automatically**, how often and when, **Save schedule**).',
        ] },
        { kind: 'note', title: 'WHAT THE CLIENT SEES', text: 'Only shared columns and charts, the whole tracker (not the viewer\'s scope), read-only. If a banner says email is not switched on for the site, nothing is sent and the attempt is recorded as failed.' },
      ],
    },
    {
      n: 19,
      title: 'Dashboards, Pulse and the Assistant',
      lead: 'What the records say, for the person looking.',
      who: ['Everyone with the Dashboard section', 'Builders: Team Lead, Assistant TL, Account Manager, Admin'],
      where: 'Dashboard; Pulse; the sparkle',
      needs: ['dashboard view / create', 'work_orders view for Pulse', 'assistant view'],
      blocks: [
        { kind: 'sub', title: 'Dashboards' },
        { kind: 'steps', items: [
          '**Needs Attention** and **Main Dashboard** are built in. Click **+** at the end of the tabs, name it, **Create dashboard**; it starts private.',
          '**Add card**: what it is called, how it looks (A single number, bar, donut, table, line, gauge, live, narrative, image, link), what it measures (How many work orders, a total, an average, or **Time between two moments** with a From and a To moment and avg or median), which records (**Every work order**, **Open work only**, **Finished work only**, or filters), **Cut it by** a field, a target; **Add card**. Cards can name a tab and a group.',
          'The **period** (All time, month, quarter, year, last 30, with ‹ ›) and the **filter bar** (client, billing entity, trade, store, dispatcher) re-ask every card.',
          '**Share…**: **Everyone who can open dashboards**, **Roles**, or people one by one. Which dashboards a role opens, and which work orders each counts, is Admin › Roles › Dashboard › Which dashboards.',
          'Click a number to open the list behind it. Every card counts only what the viewer may see.',
        ] },
        { kind: 'sub', title: 'Pulse' },
        { kind: 'p', text: 'Three columns: **Needs me now**, **Due soon**, **Watching**. Each card is an obligation (emergency acknowledgement, quote owed, schedule owed, approval follow-up, quote review owed, payment processing, SLA blown) with its owner and deadline; it clears when the thing it waits for happens. **Snooze** with a duration and a **Reason** (a critical one needs an assistant team lead or above).' },
        { kind: 'sub', title: 'The assistant' },
        { kind: 'p', text: 'Click the sparkle, ask in plain words. It looks things up through the same routes you use, so it sees exactly what you see, and it never changes anything. Thumb an answer up or down; an Admin can teach it a note from a marked answer.' },
      ],
    },
    // ────────────────────────────────────────────────────────────────────────
    {
      n: 20,
      title: 'Admin Console',
      lead: 'Users, Roles, Settings, Automations, Custom fields, Themes, Audit log, Trash, Vendors & map, Sites & assets, Integrations, Documentation. Each needs its own admin/<section> permission, checked against the person actually signed in.',
      who: ['Admin', 'Super admins'],
      where: 'Admin',
      needs: ['admin/<section> view / edit'],
      blocks: [
        { kind: 'sub', title: 'A. Users' },
        { kind: 'bullets', items: [
          'Invite: **Invite a user**, **Work email**, **Full name**, **Role**, optionally **Super admin**, **Send invitation**. The email must match their Microsoft account exactly.',
          'Change a role: the **Role** dropdown in the row (saves at once). **Super admin** switch: nobody changes their own; the last super admin cannot be demoted.',
          '**Disable** (ends sessions at once) / **Re-enable**. **Clients** column: **Assign / Edit** the clients listed on the person (widens "Only theirs" to those clients).',
          '**Adjust** (super admins only): click cells to set one person\'s permissions on top of their role (faded cells come from the role), **Save adjustments**; **Remove all adjustments** clears them.',
        ] },
        { kind: 'sub', title: 'B. Roles' },
        { kind: 'bullets', items: [
          '**New role**: **Name**, optionally **Start from** a copy, set the cells, **Create role**. Open a role, **Find a section or field…**, click a cell under View, Create, Edit, Delete or Approve, **Save role**. An unset cell follows the row above; a write grants View.',
          '**Work orders › Which work orders**: Everything or Only theirs; under Only theirs tick **Entity · <Comp>** rows. **Work orders › Status changes**: Change directly, Must request, Not allowed. **Dashboard › Which dashboards**: View per board and **Which work orders it counts**. **Technician map**: VR vendors, all or own technicians, statewide, nationwide, subcontractors, add, hire. **Admin console**: View / Edit per section.',
          '**Delete** then **Confirm**: not built-in roles, not roles that still have users.',
        ] },
        { kind: 'sub', title: 'C. Custom fields and statuses' },
        { kind: 'bullets', items: [
          '**New field**: **Name**, **Type** (Text, Long text, Dropdown, Checkbox, Date, Date & time, $ amount, Number, People, Phone number, Link, Address, Attachment, Function, Rating), **Dropdown values** one per line, **Create … field**. Rename with the pencil; change the type in its row; drag to reorder; edit values in **Options** (**Save values**). Fields are never deleted.',
          '**Add work order** column: **Not on the form**, **On the form**, **Required**.',
          '**Statuses**: in a phase card, **Add a status to …**, a colour, **Add**; pencil to rename; trash then **Delete status** (only when empty). **New phase** becomes a list tab; only an empty, non-built-in phase can be deleted.',
          '**Check-in method by FM**: **FM company**, **Method**, **Detail**, **Add**.',
        ] },
        { kind: 'sub', title: 'D. Settings' },
        { kind: 'table', head: ['Card', 'What it sets'], rows: [
          ['Authentication, Server, Database, Contents', 'Read-only: how the instance is configured and how much it holds.'],
          ['Holidays', 'The days the quote clock skips: Day, Name, Add; edit or remove in the table.'],
          ['Sub-categories', 'Per trade; Rename, Switch off / on. Suggestions for the Sub Category field.'],
          ['Add work order layouts', 'Per client and / or trade: Hidden, Optional or Required per field. The most specific wins; Client and Trade are never hidden.'],
          ['Fault and action codes', 'The code and What it means; switched off, not deleted.'],
          ['Tax rates', 'Name, %, State, Make default. Nothing on file is recomputed.'],
          ['Document templates', 'Per kind (quote, invoice, purchase order): company name, letterhead, terms, footer; Use it.'],
          ['Approval tiers by amount', 'Add a band: From $, Up to $, Roles, per kind (payment, vendor bill, invoice).'],
          ['SharePoint folders', 'Three switches (client folder, work-order folder, approved files copied), the site URL, library and path templates. A switch files only records created after it was turned on.'],
          ['Work-order PDFs', 'Per kind (Work order, Request): fields and order, title, skip empty, note.'],
        ] },
        { kind: 'sub', title: 'E. Automations' },
        { kind: 'steps', items: [
          '**New automation**, **Name**.',
          '**Trigger**: **A work order is created**, **A field changes** (which field or Any field; optionally the value, a comparison, or another field it must pass), or **Manually enrolled**; optional wait. **Next**.',
          '**Applies to**: Work orders. **Next**.',
          '**Conditions**: **+ Add a condition** (field, test, value), AND / OR with brackets. **Next**.',
          '**Actions**: **+ Add an action**: **Set a field** (empty clears) or **Raise an approval task** (type, optional role).',
          '**Review and turn on**. Each rule is a card with a switch, its run log (When, Work order, Result), edit and delete. Visit-owned and computed fields cannot be set; a rule never triggers itself.',
        ] },
        { kind: 'sub', title: 'F. Themes, Audit log, Trash' },
        { kind: 'bullets', items: [
          '**Themes**: click **Blackout** or **Daylight Dispatch** (this browser).',
          '**Audit log**: **From**, **To**, **User**, **Change**, **Search**; **Newer / Older**; **Export CSV**. Nobody can edit or delete a row.',
          '**Trash**: **Restore** a deleted work order. Nothing is removed permanently.',
        ] },
        { kind: 'sub', title: 'G. Vendors & map, Sites & assets' },
        { kind: 'bullets', items: [
          '**Vendors & map**: **Search radius (miles)**, **Daily alert at**, **Warn when a vendor\'s COI is missing or expired**, **Save**; **Preferred vendors** (Client and / or Trade, State, City, Vendor, Rank, **Add**); **Required fields**; **Dispatch offers** (**Allow dispatch offers**, start by itself, hours to answer); **Vendor invoicing rules**; **Suggested vendors** (how many, automatic fill, order of tie-breakers, hard filters); the lists (statuses, brand sources, trades, skills, consumables); map use.',
          '**Sites & assets**: site types and asset categories (add, rename, switch off); **Site access** per person (nobody listed = no restriction).',
        ] },
        { kind: 'sub', title: 'H. Integrations' },
        { kind: 'p', text: 'One row per connector (Ecotrak, ServiceChannel, Corrigo, Quo, outgoing email, escalation mailbox webhook, Claude, SharePoint, file storage, Microsoft sign-in) with its mark, what it does, whether it is set up on the server and one switch. Off makes every button that uses it stop with the reason shown where the button was; keys stay on the server. Microsoft sign-in is always on. Each flip is logged.' },
        { kind: 'sub', title: 'I. Documentation' },
        { kind: 'p', text: 'This page: **BRD**, **SOP** and **Lifecycle** tabs; **Print / Save as PDF**, **Download Markdown**, **Download Word**. The appendix is read from the live instance each time the page opens; the revision history is the migration ledger.' },
      ],
    },
  ],

  successMetric:
    'The One is working when a work order moves from the client\'s system to a paid invoice without a spreadsheet, a Teams reminder or a re-keyed form: the right dispatcher gets it complete, the technician is found in seconds, the quote is out inside 48 business hours, every approval is taken by the right tier in one inbox, the technician is paid from the record, the client sees exactly what was meant for them, and every step can be read back in the audit log.',

  matrix: [
    { role: 'Team Lead / Assistant TL / Account Manager', procedures: [1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19] },
    { role: 'OM (dispatcher) / Senior OM', procedures: [1, 2, 6, 7, 8, 9, 10, 11, 12, 16, 19] },
    { role: 'OM Under Probation / Ops Coordinator', procedures: [1, 2, 6, 7, 8, 10, 11, 12, 19] },
    { role: 'Operations Admin', procedures: [1, 2, 4, 5, 6, 8, 9, 16, 19] },
    { role: 'Accounts Payable', procedures: [1, 2, 10, 12, 19] },
    { role: 'Accounts Receivable', procedures: [1, 2, 13, 19] },
    { role: 'VR Officer', procedures: [1, 2, 15, 19] },
    { role: 'Sales', procedures: [1, 2, 19] },
    { role: 'Admin / Super admins', procedures: [1, 2, 3, 5, 6, 14, 19, 20] },
  ],
};
