// 0075 · BRD part: vendors, technicians and dispatch.

import type { DocPart } from '../types';

export const FIELD_PART: DocPart = {
  key: 'field',
  title: 'Vendors, technicians and dispatch',
  intro:
    'Technicians are external subcontractors, so finding the right one near the job is a core module. This part is The One\'s own copy of what VR - CRM and Tech Locator do, plus the suggestion and dispatch logic built on top; those two apps keep running untouched until the data moves.',
  modules: [
    {
      key: 'vendors',
      title: 'Vendor and technician records',
      where: 'Sidebar › Vendors: List · Board · Tasks · Alerts · Data quality · Performance · Coverage map; the vendor page.',
      purpose: 'One table for both kinds: vendors the VR team recruited and technicians dispatchers have worked with, with the profile, documents, compliance, notes and history.',
      value: 'The vendor network is a shared asset instead of spreadsheets and memory; compliance is derived from documents, not ticked by hand; nobody loses a good technician when a dispatcher leaves.',
      users: ['VR Officer', 'Team Lead', 'Assistant TL', 'Account Manager', 'Admin'],
      features: [
        {
          name: 'The record',
          what: 'General (Name, Kind, Status, Brand source, Owner, Priority High / Medium / Low, Email, Legal business name, DBA); Trade (Primary trade, Secondary trades); Location and coverage (City, State, ZIP, Max travel radius, Covers the whole state, Covers nationwide, Other states covered); Availability and rates (Emergency same day, After hours, Weekends, Holiday emergency as Yes / No / Not asked; Estimated response time; Regular hourly, After-hours, Weekend / emergency rates, Trip charge, Diagnostic fee, Minimum charge; Accepts payment after 30 days; Payment methods ACH / Credit / Wire / Bank Transfer / Zelle / Other); Primary contact (Contact name, Role, Dispatch phone, Billing email); Compliance (W-9 received, MSA signed, COI received, COI approved as Yes / No / Pending) for VR vendors, or Technician › Subcontractor for technicians; Notes; trade-specific profile sections (Company, Coverage area, Plumbing, HVAC and refrigeration, Electrical, Handyman, Workflow expectations, Insurance and license, Follow-up and first job). Side cards: Phones (+ Add a phone), Other contacts, Worked with (which dispatchers logged a visit, hired or added them), Preferred for, Work orders (hired list), Change history. Header chips: Possible duplicate of <name>, Missing information, Not on the map, Owner · <name>. Placed on the map from the ZIP, else the city, from our own geo tables.',
          value: 'Everything a dispatcher asks on the phone is already on the card.',
          controls: [
            { label: 'Add vendor / Edit / Save changes / Cancel', does: 'Creates or edits; a new VR vendor starts NEW with the creator as owner, a new technician starts ACTIVE.' },
            { label: '"This may already be on file." › Go back and check / Add anyway — flag as a possible duplicate', does: 'A name or phone match (phone only for technicians) is refused until flagged; flagging opens a duplicate review.' },
            { label: '"Still needed: …" › Go back and fill them in / Add anyway — flag for review', does: 'A VR vendor missing a required field is refused until flagged; flagging opens a missing-information review that closes itself once filled.' },
            { label: 'Remove', does: 'Soft delete: "They leave the list and the maps. Its payments, bills and visits keep pointing at it, and the change history stays." Open tasks close, twins lose their duplicate flag.' },
          ],
          rules: ['Status and brand source must be listed values; a phone must be a number; a dropdown value no longer on the list is kept on save.', '"Only theirs" = owner, creator or a dispatcher link; outside it a vendor answers 403 and the list shows a "Yours only" chip; bulk edits skip rows outside the scope ("N left alone").'],
          permissions: ['vendors view / create / edit / delete', 'vendors/scope view'],
          audit: ['vendor_created', 'vendor_updated', 'vendor_deleted'],
          since: '0057',
        },
        {
          name: 'Compliance, documents and insurance dates',
          what: 'Documents (W-9, MSA, Certificate of insurance with "Company the certificate names", Other document; PDF, images or Word up to 3 MB; rename, remove) upload to private storage; a W-9 marks W-9 received, an MSA marks MSA signed, a COI marks COI received, resets that company\'s checklist to Pending, closes an open COI fix and opens a COI review. The checklist per company (Certificate holder is correct, Additional insured is named, General liability meets $1M / $2M, Workers comp, Commercial auto, Waiver of subrogation) is ticked by any vendor editor; the verdict (Approve / Send back) is a reviewer\'s decision in Tasks; COI approved rolls up Yes only when every company with a certificate is approved. Insurance dates (type, company or Any company, Expires on) keep history: a superseded date is struck through and no longer counts.',
          value: 'Compliance is a fact computed from paper, and expiry is noticed before the job.',
          rules: ['Derived status: EXPIRED when a current insurance date is past; else REJECTED when COI approved is No; else APPROVED when W-9, MSA and COI are received and the COI approved; else IN_REVIEW when any is in; else MISSING_DOCS. A New / Interested / Ready vendor turns Active when approved.', 'Hiring warns ("<type> expired on <date>", "No certificate of insurance on file"); technicians never warn.'],
          permissions: ['vendors/documents create / delete', 'vendors edit (checklist ticks, insurance dates)', 'vendors/review approve (verdict)'],
          audit: ['vendor_document_added', 'vendor_document_renamed', 'vendor_document_removed', 'vendor_coi_checklist_updated', 'vendor_coi_approved', 'vendor_coi_sent_back', 'vendor_expiry_added', 'vendor_expiry_removed'],
          since: '0058',
        },
        {
          name: 'Notes, blacklist, calls and emails',
          what: 'Notes on the record (and from the map card: Add note, Notes / Hide notes, carrying the WO number); Mark blacklisted with a required reason ("Say why — a blacklist needs a reason"; everyone sees the flag and the reason); Clear blacklist ("Clearing a blacklist is a manager\'s decision"). Log a call (What was said, One-line summary, Link to the recording, Outcome that may set the status); Log an email (Subject, What it said — "This records an email you sent from your own mailbox. The One does not send it."); edit and remove; the last call feeds the Last contact column.',
          value: 'Bad experiences are shared with the whole team, not just remembered.',
          rules: ['A blacklisted vendor is never suggested, cannot accept a dispatch offer, cannot get a portal link and cannot be set as the responsible vendor; hiring from the map warns and goes through. The owner is told by a notice.'],
          permissions: ['vendors/blacklist create / edit', 'vendors edit (calls, emails)'],
          audit: ['vendor_note_added', 'vendor_blacklisted', 'vendor_blacklist_cleared', 'vendor_call_logged', 'vendor_call_edited', 'vendor_call_deleted', 'vendor_email_logged'],
        },
        {
          name: 'Tasks, alerts and data quality',
          what: 'Tasks: All open · N and per type (Possible duplicate, Missing information, COI review, COI fix, Task), Done · N (last 30 days); Add a task… for me or a person; actions Keep both / Remove this one, Acknowledge, Approve / Send back ("What needs fixing?" → a COI fix for the owner), Mark fixed (re-raises the review), Mark done. Today\'s target card (Nationwide x / y, Statewide x / y, counted from the vendors a rep added today). Alerts: All / Expired / Within 2 weeks / Within a month ("Only the latest date of each insurance counts"). Data quality: duplicates by phone, name or email with age chips and Remove; Missing information (with "· unusable" for an invalid email or a short phone; placeholders like n/a or tbd count as empty); Not on the map.',
          value: 'The VR team\'s day is a queue, and the database cleans itself.',
          rules: ['One open review per type, vendor and company; a personal task is closed by its assignee or a reviewer; giving tasks to others and setting targets need the review right.'],
          permissions: ['vendors/review approve', 'vendors delete (remove a duplicate)'],
          audit: ['vendor_task_decided', 'vendor_duplicate_kept'],
        },
        {
          name: 'List tools',
          what: 'Header chips VR vendors · N, Technicians · N, Blacklisted · N; filters (name, email or phone; trades, states, statuses, owners / No owner, paperwork, a flag: Possible duplicates / Missing information / Not on the map / Blacklisted); advanced filters ("Show vendors that match all / any of these", up to 20 rules over 40 fields and 18 tests); Columns (22, "kept for you on every device", Name always shown); Saved lists… / Save as a list (Name; Who sees it: Only me / Managers / Everyone with the Vendors section); Look up a list (phone numbers, names or emails, up to 300 lines → on file or Not on file); the bulk bar (N selected, Select all N that match; Edit one field: Status, Owner, Primary trade, State, City, Brand source; Remove; "Each record is changed and logged exactly as if you had edited it by hand"); Export CSV (26 columns, 20,000 rows, logged); the Board by status (40 cards a column, drag or Move to…); Performance (Jobs, SLA met / missed, Recalls, Temp. fixes, Response hours from hire to first check-in, Offers taken, Billed, Bill checks, for work orders received in a date range; a job counts when the vendor is responsible or hired on it); Coverage map (every placed location; filters Trade / State / Status and kind chips).',
          value: 'The CRM\'s list features without leaving The One.',
          permissions: ['vendors/lists create', 'vendors/export view', 'vendors edit (board moves, bulk edit)'],
          audit: ['vendors_exported'],
          since: '0059',
        },
        {
          name: 'Import',
          what: '1 The file (VR vendors or Technicians; a CSV of up to 2,000 rows); 2 Which column is which (Leave out; "Brand source for rows that name none"; Check the file); 3 What will happen (rows, ready, already on file, missing required fields, unreadable cells, without a name); duplicates: Skip them / Skip them and list them in a report / Add them anyway, flagged as possible duplicates / Fill in the record already on file; missing fields: Add them, flagged for review / Leave them out; Import N rows; Import finished with Download the duplicates report; Earlier imports. Rows go up in chunks ("Rows already sent were saved; the rest were not."); an unreadable cell is reported and left empty, never guessed.',
          value: 'VR - CRM and Tech Locator data (exported read-only by a script) comes in through the same wizard.',
          permissions: ['vendors/import create'],
          audit: ['vendors_import_started'],
          since: '0058',
          deferred: ['The data transfer from the two apps has not been run.'],
        },
        {
          name: 'Skills, inductions, consumables',
          what: 'Skills (Add a skill from the admin list, Level Basic / Skilled / Expert, Certified until, a "Certificate expired" chip); Inductions (Induction, For client, Completed on, Runs out on; Not done yet / Current / Expired); Consumables used on work orders from the Checklist tab.',
          value: 'Who may do what, and with what, is on the card.',
          permissions: ['vendors edit'],
          audit: ['vendor_skill_added', 'vendor_skill_removed', 'vendor_induction_added', 'vendor_induction_updated', 'vendor_induction_removed'],
          since: '0066',
        },
        {
          name: 'Vendor portal',
          what: 'Two kinds of link per vendor: Onboarding link (30 days) and Job portal link (180 days; up to two years), shown once ("Copy it now and send it to the vendor yourself: it is shown only this once, and nothing is emailed."), listed Live / Off with open counts and Revoke; the token is stored hashed. The vendor sees Jobs offered to you (Accept this job / Decline with "Why not?", "Please answer by <time>"), Your open jobs and Finished in the last 30 days in a fixed shape (no money, no internal notes), Your part (responsible vendor or technician), When will you be there? (Give / Change ETA, written to the work order and logged as given on the portal), Note for the dispatcher (copied to the work order as an internal comment from the portal, the assignees told; 30 an hour), an expired-insurance banner, and the onboarding form (Your business, What you do, Rates, Who we talk to, Insurance) that waits until one of us clicks Accept and fill the record or Send back.',
          value: 'Vendors self-serve what they need without an account and without seeing the inside.',
          rules: ['A blacklisted vendor gets no link; one waiting form at a time; five submissions a day; portal writes are signed by the Vendor portal service principal; documents cannot be uploaded there yet.'],
          permissions: ['vendors/portal view / edit'],
          audit: ['vendor_portal_link_created', 'vendor_portal_link_revoked', 'vendor_onboarding_accepted', 'vendor_onboarding_rejected', 'comment_added (source vendor_portal)'],
          since: '0066',
        },
      ],
    },
    {
      key: 'techmap',
      title: 'The technician map, suggested vendors and the dispatch cascade',
      where: 'A work order › People tab › Technicians card (Find a technician), Suggested vendors card, Dispatch offers card; Admin › Vendors & map.',
      purpose: 'Find the right person near the job: the map around the site, the top few suggestions by rule and by fit, and an optional cascade that offers the job to preferred vendors in turn.',
      value: 'The choice of vendor is made from distance, coverage, history and compliance in seconds, with the hand-picked preferences first; a dispatcher never sees more of the database than one job needs.',
      users: ['OM (dispatcher)', 'Senior OM', 'Ops Coordinator', 'Team Lead'],
      features: [
        {
          name: 'The map',
          what: 'Opens from a work order only, centred on it, radius from Admin (100 miles); filters Trade (multi, starting on the work order\'s trade), Availability (Emergency same day, After hours, Weekends, Holiday emergency), Show (VR vendors, Technicians or My technicians, Local, Statewide, Nationwide, Top 5 technicians by jobs, Hide blacklisted); result tags Hired, Preferred #n, Blacklisted, Yours, "N mi"; a vendor with no placed city is pinned at the work order; up to 600 results; each open logged and a daily alert in Admin. Pin cards: phones (tap to call), rates, trip charge, response time, coverage, compliance, Add note / Blacklist, Hire for <WO#> / Take off <WO#>. Add a technician (Name, Phone, City, State, ZIP, Trade, "Hire for <WO#> straight away"): a phone already on file links the record to you instead ("the technician is yours now too"); an unplaceable city is refused.',
          value: 'Tech Locator inside the work order, with the dispatcher\'s own book on the same map.',
          rules: ['"Theirs" = technicians the person added, hired, or logged a visit with; a released technician can be re-hired.'],
          permissions: ['vendor_map view (open) / create (hire)', 'vendor_map/* rows for what is shown', 'vendor_map/add create'],
          audit: ['tech_hired', 'tech_released', 'tech_added (created or linked)'],
          since: '0056 / 0057',
        },
        {
          name: 'Suggested vendors',
          what: 'The top few for the work order: the hand-picked preferred rules first (client, trade, state, city; most specific wins, then rank), then an automatic fill of vendors that pass the hard filters (filed under the trade, covering the location by radius / statewide / nationwide, and taking same-day emergencies when the work order is an Emergency) sorted by a fixed order of tie-breakers (worked for this client before, distance, paperwork, jobs done with us, hourly rate). Rows: Preferred #n / Hired, Hire, Call, a compliance warning line. Blacklisted vendors never appear; a hand-picked vendor is listed however far away.',
          value: 'The best five are on the card before the dispatcher searches.',
          permissions: ['vendor_map view (and its rows decide which kinds appear)'],
          since: '0069',
        },
        {
          name: 'Preferred vendors',
          what: 'Rules in Admin › Vendors & map: Client and / or Trade ("Pick a client, a trade, or both"), State, City (needs the state), Vendor, Rank 1–9, Note ("Why — contract, pricing…"), Remove; a duplicate rule is refused.',
          value: 'Client-mandated vendors and house favourites come first automatically, on the map, in the suggestions and in the cascade.',
          permissions: ['admin/vendors edit'],
          audit: ['preferred_vendor_created', 'preferred_vendor_updated', 'preferred_vendor_deleted'],
        },
        {
          name: 'Dispatch cascade',
          what: 'Off by default (Admin › Vendors & map › Dispatch offers: Allow dispatch offers, Start by itself when a work order is added with no vendor, Hours a vendor has to answer, 1 to 168, default 4). On the People tab\'s Dispatch offers card: Offer to preferred vendors / Offer to the next vendor, Stop, They accepted / They declined, and the table (#, Vendor, Offered, Answer, Answered; Offered / Accepted / Declined / No answer / Stopped). The work order is offered to the preferred vendors of its client, trade, state and city in turn (automatic picks follow when Admin allows it); a decline or a lapsed clock moves it on (on every read and on the hourly cron); accepting sets the responsible vendor; the vendor can answer from the portal.',
          value: 'Routine jobs find their vendor without a dispatcher on the phone.',
          rules: ['Refusals: offers switched off; the work order already has a responsible vendor; an offer is already out; no preferred vendor left. A blacklisted vendor cannot accept; a hand assignment ends the run; switching the setting off cancels every live offer; auto-start happens only with "Start by itself".'],
          permissions: ['vendors/dispatch view / edit + work_orders edit'],
          audit: ['field rows "Dispatch offer" and "Vendor" on the work order'],
          since: '0066',
        },
        {
          name: 'Who sees which technicians',
          what: 'Admin › Roles › Technician map (view = open, create = hire): Which technicians (All technicians / Only theirs), VR vendors, Statewide vendors, Nationwide vendors, Subcontractors, Add a technician; and under Vendors: Which vendors (Everything / Only theirs), Notes and blacklist, Review queue, Documents, Import from CSV, Export to CSV, Saved lists, Vendor portal, Dispatch offers.',
          value: 'The baseline dispatcher sees their own list plus the vendor network for one search; widening is a tick.',
        },
        {
          name: 'In-app notices',
          what: 'One notice per person per thing that happened to them, in the bell under "For you": a task given to you, a review opened (to everyone whose role may review, plus super admins), a decision on your task, a vendor handed to you, your vendor blacklisted, an insurance date on your vendor within 30 days / 14 days / expired (raised on the bell\'s read, at most every ten minutes), an onboarding form received, a note from the portal, a dispatch answer, a credit note to approve. Read notices are pruned after 60 days; nobody is told about their own act.',
          value: 'Nobody has to poll the Tasks view.',
          since: '0059',
        },
        {
          name: 'Vendors as a dashboard source',
          what: 'Cards can count or total vendors (status, kind, trades, state, city, owner, added by, brand source, priority, paperwork, coverage, W-9 / MSA / COI, blacklisted, jobs, rates, dates) following the viewer\'s vendor scope; the shipped Vendors and Vendor Performance boards use them.',
          value: 'Recruiting coverage is measured, not felt.',
        },
      ],
    },
  ],
};
