// 0075 · BRD part: money — quotes, payments and vendor bills, receivables,
// contracts, purchasing. Labels are the ones in the JSX.

import type { DocPart } from '../types';

export const MONEY_PART: DocPart = {
  key: 'money',
  title: 'Money: quotes, payments, invoices, contracts and purchasing',
  intro:
    'Money flows both ways on a work order: the client is quoted and invoiced (receivables) and the technician is paid (payables). Every figure is computed in integer cents, every document is numbered, and the two sides meet in Cost, Total Invoiced and Profit on the work order.',
  modules: [
    {
      key: 'quotes',
      title: 'Quotes',
      where: 'Sidebar › Quotes; the Client quote card on a work order\'s Finances tab; the quote builder; /work-orders/:wo/quote/print.',
      purpose: 'One quote per work order, built from the technician\'s report, priced from the client contract, submitted, approved and sent, then printed.',
      value: 'Quotes are consistent across dispatchers, priced from the contract rather than memory, approved by the right role, numbered, and never re-priced after approval.',
      users: ['Senior OM', 'Team Lead', 'Assistant TL', 'Account Manager'],
      features: [
        {
          name: 'Creating the quote',
          what: 'Create quote on the Client quote card issues the number (Q-<entity>-<year>-<n>, per billing entity per year, never reused; a work order with no entity gets Q-Q-…), snapshots the contract in force and its overtime multiplier, pre-fills Bill to with the client and opens the Incurred section as "Work already performed". One quote per work order ("A quote already exists for this work order").',
          value: 'The price basis is frozen on day one.',
          permissions: ['quotes create and quotes edit (both are checked)'],
          audit: ['quote_created'],
          since: '0003 / 0048',
        },
        {
          name: 'The builder',
          what: 'Header: Rev n, the number chip ("issued per billing entity per year, never reused"), Print / PDF, the autosave chip (Not saved yet / Unsaved edits / Saving… / Draft saved · n ago / Draft not saved) and a leave guard ("You have unsaved edits to this quote — Discard & leave / Keep editing"). Document card: Document type (Quote / Proposal / Estimate), Bill to, Ship to / site. Incurred: Tech reported that… (required) and the scope list "Required is to…" (Enter adds a line). Options: Option name and Option narrative (both required), Include in summary switch, Remove; "Show all options as separate quotes" is disabled ("Coming in a later sprint"). Lines: Type (Service / Labor / Part / Material), Description, Qty, UOM (hr, ea, trip, day, lot, ft, sq ft), Unit price, Markup %, Tax %, Day (Day 1–5, stored verbatim), OT, Amount. Specs card "Equipment & part specs — Not sent to the client". Note to Customer. Summary text (Edit text / Save text; pinned text stops auto-sync). Money rail: NTE meter (warns at 85 %: "Past the 85% mark — $X of headroom", "$X over the client NTE"), "Priced under <contract> · $/h · trip · OT n×" or "No contract covers this work order — house rates, OT 1.5×", Sales tax (typed, or Apply a rate… from the tax-rate list), Line tax, Total Cost / Profit / "n% margin".',
          value: 'A quote that reads the same to every client and adds up the same on screen and in print.',
          controls: [
            { label: 'Add line / Add scope line / Add option', does: 'Builds the document; invalid lines are excluded from the subtotals, not zeroed.' },
            { label: 'Submit for approval', does: 'Draft → pending approval, once the red chip lists nothing to fix.' },
            { label: 'Approve & Send to CMMS', does: 'Approves, then sends (two calls: if sending fails the quote stays approved and the button reads Send to CMMS). Sending posts a client-visible comment "Quote for $X submitted for approval — …".' },
            { label: 'Reject with note', does: 'From pending approval OR approved back to draft: the revision number goes up, the approver is cleared, an internal comment "Quote returned to draft — <note>" is posted.' },
            { label: 'Print / PDF', does: 'The printable document with the default template\'s letterhead and terms.' },
          ],
          rules: [
            'Editable only while draft or pending approval ("A quote in status … can no longer be edited").',
            'Validation chip: Tech report is required; at least one scope line; Option X needs a name / a narrative; Description, Qty (> 0) and Rate (> $0) per line; Tax and Markup are percentages; Sales tax must be a number.',
            'Amount = qty × rate × (1 + markup) × (overtime multiplier if OT; the contract\'s overtime ÷ standard rate, else 1.5). Grand Total = the options marked Include in summary plus their line tax; the Incurred subtotal is context and is NOT added twice.',
            'Approving and sending are locked while an NTE override is open on the work order ("On hold — decide the NTE override under Approvals first"); rejecting never is.',
            'The work order\'s money block binds only to an approved or sent quote.',
            'The builder\'s locked tips name roles ("Requires ATL or above", "Requires Senior OM or above") although the gate is the permission tree.',
          ],
          permissions: ['quotes edit', 'quotes approve (covers reject and send)'],
          audit: ['quote_updated (whole snapshots; an autosave that changed nothing logs nothing)', 'quote_submitted', 'quote_approved', 'quote_sent', 'quote_rejected', 'comment_added'],
        },
        {
          name: 'The printed quote',
          what: 'Letterhead, terms and footer from the default document template; Revision, Currency, Client ref, Bill to (the client) and Ship to (the site); the incurred block prints as "Work performed · Billed with the work order"; the printed Total = Grand Total + sales tax; "This <quote | proposal | estimate> is valid for 30 days from the date above."; "Priced under <contract>."; internal fields (specs, cost, profit, NTE) are left off. Save as PDF is the browser\'s print dialog.',
          value: 'What the client receives is exactly the summary, nothing internal.',
        },
        {
          name: 'Quotes queue',
          what: 'Lanes All · Drafts · Pending approval · Approved · Sent (status label "Sent to CMMS"); chips "Awaiting approval $…" / "Approved or sent $…"; columns Quote #, WO #, Client · Title, Quote status, Grand total, Updated, Document (Print / PDF); Approve & send and Decline (note required) on the row.',
          value: 'Managers approve from the list; the quote-review obligation (4 business hours) is measured on this queue.',
          permissions: ['quotes view', 'quotes approve'],
        },
        {
          name: 'Contract pricing',
          what: 'When a quote is created the contract in force for the work order is snapshotted with its overtime multiplier (overtime ÷ standard, rounded to three places); a deleted contract leaves the snapshot intact.',
          value: 'An approved quote never changes price because a rate card was edited later.',
          since: '0046',
        },
        {
          name: 'AI quote draft from a call',
          what: 'From a Quo call with a transcript (409 "This call has no transcript yet — wait for Quo, or paste it" otherwise), Draft a quote with AI sends the transcript, the work order and its contract rates to Claude and returns a draft in the builder\'s own shape with assumptions and missing information. The review page shows it in the builder\'s editors beside the transcript (overtime priced at 1.5× on the page; the quote applies its contract\'s own multiplier), autosaves edits to the draft (not logged), and offers Discard, Redraft / Draft again, "N to fix before approval" and Submit quote, which runs the ordinary create and update.',
          value: 'The first draft is written while the dispatcher is still on the phone; prices are never invented (client price stated, vendor cost plus contract markup, contract rate, or a listed gap at $0).',
          rules: [
            'Drafting needs the Claude integration switched on and quotes edit; Submit also needs quotes create when the work order has no quote.',
            'A submitted draft cannot be redrafted; an empty draft cannot be submitted.',
            'A quote with content is replaced only after confirming ("Replace it with this draft" / "Keep the current quote"; the number, sales tax and document fields are kept); an approved or sent quote is never touched (409 QUOTE_LOCKED: "reject it back to draft before replacing it").',
          ],
          permissions: ['work_orders/calls create', 'quotes edit', 'quotes create'],
          audit: ['quote_ai_drafted', 'quote_ai_redrafted', 'quote_ai_submitted', 'quote_ai_discarded'],
          since: '0054',
          deferred: ['Needs ANTHROPIC_API_KEY on the server; pricing references from past quotes (vector search) are next.'],
        },
      ],
    },
    {
      key: 'payments',
      title: 'Technician payments and vendor bills',
      where: 'Sidebar › Payments; the Payment requests and Vendor bills cards on the Payables tab; Request payment on a work order.',
      purpose: 'The payables queue: a request per vendor payment, approved by the right role, handed to Yoda (the payment tool) and marked paid; the vendor\'s own bills and credit notes beside it.',
      value: 'Technicians are paid fast and traceably, which keeps good technicians; the work order\'s Cost is the sum of what was actually approved, not a typed guess.',
      users: ['OM (dispatcher)', 'Team Lead', 'Assistant TL', 'Account Manager', 'Accounts Payable'],
      features: [
        {
          name: 'Requesting a payment',
          what: 'Request payment: the payee is a Vendor record, or a name and phone typed by hand ("Technician not in the vendor list? Enter a name and phone manually"); optional Recipient ("Add recipient — Send payment to someone other than the technician" / "Pay the technician instead"); Purpose; Amount (a plain decimal above $0); Method (Zelle · ACH transfer · Check · Company card · Cash App); a note "Anything AP needs to know…". The attachments drop zone is drawn disabled (not functional yet). Submit is held until the technician, phone, purpose and amount are in.',
          value: 'One form, enough detail for AP to pay without a chat.',
          permissions: ['payments create'],
          audit: ['payment_requested'],
          since: '0022',
        },
        {
          name: 'The Payments queue',
          what: 'Lanes Needs approval · To process · All requests · Vendor bills (the default lane follows the person\'s grants: approvers land on Needs approval, AP on To process; ?lane=bills deep-links). Dialogs: "Approve this payment? … Approve payment", "Reject this payment — Why is it being rejected? — Reject with note", "Send to Yoda — Yoda reference (e.g. YD-10422) — Sent to Yoda", "Mark this payment paid? … Mark paid". Chips "Awaiting approval $" / "Approved, not yet paid $". A locked verb says why: "Requires payment approval rights", "AP processes payments", "<band> needs a role allowed for the band (rule 6.2.3)", "On hold — the NTE override on this work order has to be decided first (rule 1.5.2)".',
          value: 'One queue with a clear owner per lane and the reason on every locked button.',
          rules: [
            'requested → approved → sent to Yoda → paid, or rejected; Reject is allowed from requested or approved; the API also allows Mark paid straight from approved (money sometimes goes out by hand) though the page offers it only after Send to Yoda.',
            'Approve and Send to Yoda are held by an open NTE override; Reject and Mark paid are not.',
            'A rejection posts an internal comment "Payment request of $X to <payee> (<purpose>) rejected — <note>".',
            'On the work order, Total paid counts paid requests only; Payables total counts everything not rejected.',
          ],
          permissions: ['payments approve', 'payments/process edit'],
          audit: ['payment_approved', 'payment_rejected', 'payment_sent_to_yoda', 'payment_paid', 'comment_added'],
        },
        {
          name: 'Cost follows the payments',
          what: 'Cost = the sum of the work order\'s accepted requests (approved, sent to Yoda or paid), re-derived inside every decision; rejecting takes one back out and rejecting the last accepted one clears Cost. The system write is an ordinary field_updated row stamped via payment, re-derives Profit and runs the automations, which is how the NTE override is raised.',
          value: 'Cost on the work order is a fact, and the Done gate and Profit read a fact.',
          rules: ['The lock is conditional: a hand edit is refused only while the field\'s latest audit row is a system write with a value; a work order with no accepted request still takes a typed Cost, and figures typed before the rule stay correctable.'],
          brd: ['11.3.2'],
        },
        {
          name: 'Approval tiers by amount',
          what: 'Bands per decision kind (Payment requests, Vendor bills, Client invoices) naming the roles allowed inside them; From $ (inclusive), Up to $ (exclusive; blank = no ceiling), Roles, Add band; the first band in position order wins; a band with no roles restricts nobody; super admins are never restricted. The row carries the tier so the button is locked with the reason before the click; the API answers 403 "<what> of this amount (<band>) needs one of: …".',
          value: 'A $3,000 payment cannot be approved by someone whose authority stops at $500.',
          permissions: ['admin/settings edit to set the bands'],
          audit: ['approval_tier_created', 'approval_tier_changed', 'approval_tier_deleted'],
          brd: ['6.2.3'],
          since: '0047',
        },
        {
          name: 'Vendor bills',
          what: 'Record bill (the work order id, Vendor, Their invoice #, Received date (today by default), due date, lines) → received → approved → paid, or disputed (a note is required: "Say what is being disputed"; posts an internal comment; Resolve returns it to received) or void. Lane chips "On file, not agreed / Approved, unpaid / Past due"; each row shows its tier label and a warning chip when an invoicing rule trips.',
          value: 'The vendor\'s paper is matched to the work order and checked before it is paid.',
          rules: [
            'Edits only while received or disputed (409 VENDOR_BILL_LOCKED). Vendor bills never feed Cost.',
            'Invoicing rules (Admin › Vendors & map) only WARN: Invoice number missing, used before, Over the work order\'s Cost, Vendor not on the work order, Billed before completion, Billed late, Credit notes that need approval; net total = total minus approved credits ("Net of credits").',
          ],
          permissions: ['payments create (record, dispute, resolve, void)', 'payments approve (approve)', 'payments/process edit (pay)'],
          audit: ['vendor_bill_created', 'vendor_bill_updated', 'vendor_bill_status_changed', 'comment_added'],
          since: '0047 / 0066',
        },
        {
          name: 'Credit notes',
          what: 'Credit note (CN-n) against a vendor bill; approved as written at or under the "Credit notes that need approval" threshold (default $250) or when the raiser may approve payments, otherwise it waits for an approver (bell notice); void needs a reason; the author may void their own pending note. Recorded as a field row "Vendor credit note" on the work order.',
          value: 'An overbilling is corrected on the record, not by hand in Yoda.',
          permissions: ['payments create (raise)', 'payments approve (approve / void)'],
          since: '0066',
        },
        {
          name: 'Payments as a dashboard source',
          what: 'Dashboard cards can count or total payment requests (amount, status, method, payee, client, dispatcher, billing entity, FM, trade, state, purpose, work order, the vendor\'s owner / trade / state); the shipped Payments and Accounting boards are built from them.',
          value: 'AP sees the backlog and the spend by dimension without an export.',
        },
      ],
    },
    {
      key: 'receivables',
      title: 'Receivables: audit and invoicing',
      where: 'Sidebar › Receivables: Audit and Invoicing tabs; the Invoice card on a work order\'s Finances tab; /invoices/:id/print.',
      purpose: 'The AR audit of completed work and the client invoice from the approved quote.',
      value: 'A pristine record before it is billed; one invoice per work order, numbered per entity and year, with figures frozen when sent.',
      users: ['Accounts Receivable', 'Admin'],
      features: [
        {
          name: 'Audit (prototype)',
          what: 'Lanes All · Major · Minor · Clean; a panel per work order with "Auto-check results", "Findings", "Suggested QC: Major / Minor", the four ticks GTG · Elise · Admin · Quote, Resolve via chips (Open work order opens the record; ClickUp task and SharePoint folder are placeholders) and the release line "Clean release — this WO is in Invoicing → Ready to invoice".',
          value: 'The shape of the Argus audit assistant inside The One, ready to be wired to real checks.',
          rules: ['PROTOTYPE: the findings (BFI, CICO, SharePoint contents, CO#, days, assignee) are seeded from the work order id, not read from systems ("External systems are stubbed in this prototype"); the queue is a sample of done and active work orders from the first 200 read; the four ticks live in the browser, are lost on reload and are not audited; the Ready lane\'s amount is the NTE or a seeded figure.'],
          deferred: ['Real auto-checks against the record, persisted and audited ticks, the SharePoint and client-system reads.'],
        },
        {
          name: 'Invoicing',
          what: 'Stages All · Proposed · Ready · Drafts · Sent · Paid; stat cards Ready to invoice / Drafts / Outstanding / Collected (30d); banners "$X is past its due date" and "N work orders are still held by the completion audit". Raise invoice drafts from the approved quote (incurred plus the options flagged for the summary, overtime folded into the unit price), else from a time-and-materials contract (hours on site to the quarter hour plus the trip charge), else one line "Work order <#>" at Total Invoiced or the NTE; Send (needs approve, passes the amount tier, refuses a zero total; due date = 30 days); Mark paid; on the work order\'s Invoice card: Send to client, Mark paid, Open in Receivables, Print / PDF. The printed invoice carries Bill to, Site, Subject, Discount, Tax and the template\'s terms.',
          value: 'The invoice says what it said when it was sent, forever.',
          rules: [
            'One invoice per work order; the number is <entity>-<year>-<n> (entity letters and digits only, else INV), claimed inside the issuing transaction and never reused.',
            'draft → sent | void, sent → paid | void, void → draft (reopen), paid is terminal; void and reopen exist in the API only (no button yet), and there is no line editor on screen yet (the lines are the prefill).',
            'Money is computed in integer cents (1.5 × 99.99 bills 149.99); the invoice total can differ from the quote\'s Grand Total because the invoice adds the incurred lines.',
          ],
          permissions: ['invoicing view / create (raise, confirm a proposal) / edit (mark paid) / approve (send)'],
          audit: ['invoice_created (with its basis: quote / contract / work order / proposal)', 'invoice_updated', 'invoice_status_changed'],
          since: '0045',
        },
        {
          name: 'Billing proposals',
          what: 'When a contract has Bill automatically on completion, landing in the Done group proposes an invoice (if none exists) and, from a time-and-materials vendor contract, a vendor bill (if none exists); at most one pending per kind. Confirm files it with exactly those lines; Dismiss ("Why not? (optional)", Keep it / Dismiss proposal) drops it and keeps the note; "Waiting for someone who can raise it." when the viewer lacks the create right. Drawn on the Finances card, the Payables card and the Proposed lane.',
          value: 'Completion drafts the paperwork; a person only confirms.',
          permissions: ['invoicing create (invoice)', 'payments create (vendor bill)'],
          audit: ['billing_proposed', 'billing_proposal_confirmed', 'billing_proposal_dismissed'],
          brd: ['6.4'],
          since: '0053',
        },
        {
          name: 'Total Invoiced follows the quote',
          what: 'Moving to Invoiced or Invoiced Not Paid stamps Total Invoiced with the quote\'s grand total, whatever the quote\'s status, when it is above zero; after that it cannot be typed while the latest audit row is the system\'s. Profit = Total Invoiced minus Cost.',
          value: 'Profit per work order is derived, not keyed.',
          deferred: ['Total Invoiced does not follow the invoice record yet ("for now the total of the quote").'],
        },
      ],
    },
    {
      key: 'contracts',
      title: 'Contracts and labor rates',
      where: 'Sidebar › Contracts.',
      purpose: 'Rate cards: hourly, overtime, double-time, trip charge and markup on parts, for a client or a vendor, an entity, some sites and trades, between two dates.',
      value: 'Quotes and invoices price from the contract in force, and the most specific card wins.',
      users: ['Admin', 'Account Manager', 'Team Lead', 'Accounts Payable'],
      features: [
        {
          name: 'Rate cards',
          what: 'New contract: Name, Whose terms (client or vendor), Vendor (blank = every vendor), Client (blank = every client), Billing entity, Account code, Kind (Time and materials / Scheduled maintenance), Starts, Ends (blank = open), Trades covered, Sites covered (store numbers or names), Notes, Active, Bill automatically on completion; rates per trade with Add rate (Standard hour, Overtime hour, Double-time hour, Trip charge, Markup on parts %). Lanes In force · All; columns Contract / Covers / Rates / Actions; Edit, Save contract, Delete contract.',
          value: 'One place for every negotiated rate.',
          rules: ['"A contract needs a name"; it cannot end before it starts; a rate is zero or more.', 'The most specific card wins: vendor name 16 > client 8 > entity 4 > trade 2 > site 1, ties to the most recent start; sites match by store number then name; a vendor card never prices a client invoice and the reverse.'],
          permissions: ['contracts view / create / edit / delete'],
          audit: ['contract_created', 'contract_updated', 'contract_deleted'],
          since: '0046 / 0053',
        },
        {
          name: 'Time and materials invoicing',
          what: 'A work order with no quote and a T&M client contract bills hours on site (every checked-out visit, to the quarter hour) at the standard rate plus the trip charge per visit; a T&M vendor contract proposes the vendor bill the same way on completion.',
          value: 'Small jobs are billed from the visit log without a quote.',
        },
      ],
    },
    {
      key: 'purchasing',
      title: 'Purchasing, tax rates, document templates and budgets',
      where: 'Sidebar › Purchasing: Requests, Requests for quotation, Purchase orders, Budgets (each shown with its own view grant); the Purchasing card on a work order\'s Payables tab.',
      purpose: 'Purchase request → request for quotation → purchase order, with budgets and AFEs that warn, tax rates to pick from, and the templates that dress the printed quote, invoice and order.',
      value: 'Parts and materials are bought with a paper trail and compared quotes, and never double-counted against the work order\'s Cost.',
      users: ['Accounts Payable', 'Team Lead', 'Admin'],
      features: [
        {
          name: 'Purchase requests',
          what: 'PR-n: New request (What is being bought, Items with + Add a line, optional Work order) → Save as draft / Submit for approval → Approve, or Reject with a Note to the requester → Ordered; Cancel the request; Back to draft from rejected or cancelled. Statuses Draft / Waiting for approval / Approved / Rejected / Ordered / Cancelled. From an approved request: Ask vendors for quotes or Raise a purchase order. Approvers and the requester are told through notices.',
          value: 'Spend is approved before it happens.',
          rules: ['Submit needs a description, at least one item, and a quantity above zero on every item; a rejection needs a reason.'],
          permissions: ['purchasing/requests view / create / edit / approve'],
        },
        {
          name: 'Requests for quotation',
          what: 'RFQ-n: items and vendors; Mark as sent to vendors (recorded, nothing is emailed; refused with no lines or no vendors); Record quote per vendor (per-line prices or a total); Quotes side by side marks the lowest total and the fastest; Close to quotes, Reopen, Cancel it; Award drafts the purchase order from the winner. Statuses Draft / Out to vendors / Closed to quotes / Awarded / Cancelled.',
          value: 'The cheapest compliant quote is chosen on the record.',
          rules: ['Award refuses a blacklisted vendor and needs purchasing/orders create as well.'],
          permissions: ['purchasing/rfqs view / create / edit'],
        },
        {
          name: 'Purchase orders',
          what: 'PO-n: draft (the only editable state) → Issue the order (refuses an empty or zero-value order) → partly / fully received (Save what arrived, never more than ordered) → Close the order; Cancel is edit on a draft, approve once issued, refused once anything was received ("close it instead"); Print / PDF with the template. Warnings on the order: vendor blacklisted, AFE over / closed / expired, "A line has no price."',
          value: 'Receiving is tracked line by line.',
          rules: ['A purchase order never writes the work order\'s Cost ("A purchase order is a document beside the work order: it does not change the work order\'s Cost.").'],
          permissions: ['purchasing/orders view / create / edit / approve'],
        },
        {
          name: 'Budgets and AFEs',
          what: 'Cost centers (unique Code, Name) and AFEs (unique AFE number, Amount authorized, Title, Valid from / to); Spent = work-order Cost plus received orders not tied to a work order, Committed = issued orders still to arrive, Used % and an over flag; filing a work order under a cost center or AFE is done on its Purchasing card.',
          value: 'Overspend is visible at the order, not at month end.',
          rules: ['Going over a budget or an AFE warns on the order and never blocks.'],
          permissions: ['purchasing/budgets view / edit', 'work_orders edit + purchasing/budgets view to file a work order'],
          audit: ['cost_center_added', 'cost_center_updated', 'budget_set', 'afe_added', 'afe_updated', 'field rows "Purchase request" / "Purchase order" on the work order'],
        },
        {
          name: 'Tax rates and document templates',
          what: 'Admin › Settings: tax rates (Name, % between 0 and 100, optional State, Make default; unique names; nothing on file is recomputed) that the quote builder\'s Apply a rate… and purchase orders pick from; document templates per kind (quote, invoice, purchase order): Name, Kind of document, Company name on the document, Letterhead, Terms, Footer, "Use it — the one template printed for this kind of document".',
          value: 'Printed documents carry the right letterhead and terms per entity without hand editing.',
          permissions: ['admin/settings edit'],
          audit: ['tax_rate_added', 'tax_rate_updated', 'doc_template_added', 'doc_template_updated', 'doc_template_deleted'],
          since: '0067',
        },
      ],
    },
  ],
};
