// 0075 · BRD part: work orders — the record, visits, sign-off sheets, statuses
// and gates, incoming, approvals, flags. The list is in woList.ts.

import type { DocPart } from '../types';
import { WO_LIST_MODULE } from './woList';

export const WORK_ORDERS_PART: DocPart = {
  key: 'work-orders',
  title: 'Work orders: list, record, visits, statuses and intake',
  intro:
    'The work order is the record everything else hangs on. This part covers how work orders arrive, how the list is worked, what the record holds, how visits and statuses move it along, and the gates that keep it honest.',
  modules: [
    WO_LIST_MODULE,
    {
      key: 'wo-record',
      title: 'The work-order record',
      where: 'Open any row. Header, action bar, tabs and the right rail; the tab lives in ?tab=.',
      purpose: 'One page that holds everything about a job: the fields, the money, the dates, the people, the visits, the files, the conversation and the history.',
      value: 'Nobody re-keys between ClickUp, Teams and a spreadsheet; the record is the single source and every tab is gated by role.',
      features: [
        {
          name: 'Header',
          what: 'WO number and client reference with Copy WO number / Copy external reference; client, store, trade; the Assignee chip (Unassigned when empty); Client NTE and Cost (red when Cost is above the NTE); priority and billing-entity chips; the status pill with Change status / Request status change (a role with neither right sees a read-only pill); the phase bar ("Pipeline inert — <status> sits outside the nine stages." for an unmapped status); aging cells Age (a warning at ten days while open or active), In status, SLA due; the Ecotrak · <status> chip; the Awaiting acceptance chip; the request banner ("→ <status> · approved by X" with Continue, or "Rejected: <reason> · by X" with Request again / Understood, and a Decide link for approvers); obligation clock chips that scroll to the Obligations card; Call; Mark as Escalated / Escalated · Clear; a fold button that keeps the header to one row per browser.',
          value: 'The state of the job in one glance.',
          controls: [
            { label: 'Change status / Request status change', does: 'Opens the status menu ("Search statuses…" or "Request a status…"); picks are tagged Needs quote, Needs parts, Needs check-out, Needs cost, Needs after photo, Needs sign-off, Not ready, Ecotrak; a request confirms "Request for <status> sent for approval".' },
            { label: 'Call', does: 'Records the intent and dials through the Quo desktop app; Just call or Call and draft a quote.' },
            { label: 'Mark as Escalated / Escalated · Clear', does: 'Sets the Escalated field; shown to whoever may edit that field (managers).' },
          ],
          rules: ['The gate tags are computed from the latest visit\'s mirrored stamps and the approved attachment kinds; the API checks every visit when the move is attempted.'],
        },
        {
          name: 'Action bar',
          what: 'Assign vendor / Re-assign vendor (Responsible vendor: Find a vendor, Hired on this work order shortcuts, Remove), Pause / Resume ("Pause this work order — Why is it paused?"), Add ETA / Change ETA (Estimated time of arrival, Expected on site, Note, Save ETA, Clear the ETA), Tag ("Tag this work order", suggested tags, Reason, Add the tag), Increase NTE ("Ask for a higher NTE": New NTE, Why more is needed, Send the request), Complete service / Edit completion (Completion note, Fault code — what was wrong, Action code — what was done, Is this a temporary fix? No / Yes — a return is needed / Not said; Clear the completion), Cancel work order ("Why is it cancelled?") / Reopen, Save as PDF (Work order "The main fields, as set in Admin › Settings"; Request "Client, site and what they asked for"). The bar also shows state chips: Cancelled — reason, Paused <when> — reason, ETA <time>, Service completed · temporary fix, the vendor, "NTE increase to $X waiting", running site events, tags with remove.',
          value: 'The Facilio-style actions a dispatcher expects, each audited and each a plain column on the work order.',
          rules: [
            'Cancel moves the work order to the first status whose name starts with "Cancel", ends an open pause, and keeps its stamp even if a gate refuses the move; Pause and Complete service are refused on a cancelled work order; Complete needs a note, a fault code or an action code, and codes must be active catalogue codes.',
            'Increase NTE: the amount must exceed the current NTE ("That is not an increase…"), a reason is required, one open request per work order; deciders (approvals/nte approve) get a notice and decide on the Cost breakdown tab (Approve — set the NTE to $X / Reject with why / the requester may Withdraw); approval writes Client NTE through the ordinary field path and the requester gets a notice. These requests are not in the Approvals inbox.',
            'A pause is a marker only; no clock stops (rule 2.4.4). Assigning a blacklisted vendor is refused.',
          ],
          permissions: ['work_orders edit', 'vendor_map view or vendors view (vendor controls)', 'work_orders/tabs/money view (Increase NTE)', 'approvals/nte approve (decide it)', 'work_orders/pdf view, unset = work_orders view'],
          audit: ['field rows: Paused, Cancelled, ETA, Tag, Vendor, NTE increase requested / approved / rejected / withdrawn, Service completed', 'work_order_pdf_saved'],
          since: '0064 / 0073',
        },
        {
          name: 'Tabs',
          what: 'All fields (default), Finances, Dates, CICO, People, Payables, Site, Parts, Flags, Overview, Checklist (n / m badge), Cost breakdown, Timelog (its permission row reads Timelog & metrics), Related, Messages (count badge), Audit trail. Each tab is a permission row (work_orders/tabs/<tab>); Checklist also carries the Job plan, Services and Consumables cards; Timelog the Technician time card (Start a timer / Stop / Log time, Billable); Related the Work permits card (Send for approval, Approve, Reject, Close the permit, Back to draft; "A permit is needed" chip), the approvals list, Same asset and Same site; People the Dispatch offers card; Payables the purchasing card.',
          value: 'A role sees the tabs of its job: AR sees Finances and the audit; a probation dispatcher does not see Payables.',
        },
        {
          name: 'Inline editing and the field catalogue',
          what: 'All fields: Search fields…, order Default / A–Z / My order (drag or arrow keys; a per-user order for every work order), View all / Show less on long text; click a value, change it, tick. Inputs follow the type (date, date-time, money with cents, number, phone, link, dropdown, people with Who\'s available? / Back to search inside the Assignee picker); booleans save on click; a formula field shows ƒ ("the formula is not wired up yet"); a visit-mirrored field says "Comes from the latest visit…". Per-field history is a panel (needs the field-history grant). Previous Assignees is kept by the system: every change appends the departed name.',
          value: 'Fields are configuration: the team adds one in Admin and it appears on the record, the list, the filters, the automations and the exports.',
          rules: [
            'Visit-owned fields (Visit Type, Check-in/out Status, Checked-in At, Checked-out At, Tech Name, Tech Phone Number, CICO Method) mirror the latest visit and cannot be typed; Quote Due Date is computed; Sign-Off Link is written by the sign-off sheet; formula and attachment subtypes are read-only.',
            'Cost is the sum of accepted payment requests once the system has written it; Total Invoiced is the quote total once stamped; Profit = Total Invoiced minus Cost.',
            'A field needs view and edit on its own path; a hidden field is absent from the payload altogether.',
          ],
          permissions: ['work_orders edit + edit on the field', 'work_orders/history view'],
          audit: ['field_updated'],
        },
        {
          name: 'Overview',
          what: 'The Obligations card first ("Nothing owed on this work order."; Snooze per row), the Soft-close checklist (Quote created, Before photos, Quote check, Admin check, GTG; an n / 5 meter), the Updates & activity feed (read-only, "N events · newest first", with a Write a message button) and the Photos card.',
          value: 'The story of the job on one tab.',
        },
        {
          name: 'Finances',
          what: 'The NTE meter ("Not fully paid"), the NTE override banner (awaiting a manager / approved / rejected), the Client quote card (Create quote / Open quote; Approve and Decline when pending), the Client invoice card (Raise invoice, "Proposed — waiting to be confirmed", Send to client, Mark paid, Open in Receivables, Print / PDF, "N d overdue"), Total Invoiced and Profit.',
          value: 'The money side of the work order with the quote and the invoice beside the numbers.',
          permissions: ['work_orders/tabs/money view', 'approvals view for the override banner'],
        },
        {
          name: 'Dates, People, Site, Parts, Flags, Payables',
          what: 'Dates: received, due, SLA due, scheduled, parts arrival, quote due ("· quote overdue" / "· overdue"). People: the seats (Assignee with Who\'s available?, AM, …), Routing, the Technicians card (Find a technician, Hire, Take off — "the record and its visits stay", Call), Suggested vendors, Dispatch offers. Site: the address fields and the Site record block (Change / Unlink / Link / Keep the current site; the asset: Choose the asset… / No asset; "Getting in:" access notes). Parts: Parts required / No parts listed. Flags: Emergency first, then the other checkboxes ("All clear" / "N raised"). Payables: Payment links, Payment requests (Request payment), Vendor bills ("Approving needs the amount\'s tier (rule 6.2.3); paying is AP\'s."), purchasing documents, payment history.',
          value: 'Each cluster of fields where the person working that part of the job expects it.',
        },
        {
          name: 'Checklist, Cost breakdown, Timelog, Related',
          what: 'Checklist: Add / Add N steps (one per line), tick, remove, "N of M done"; Apply a job plan; services and consumables used. Cost breakdown: Revenue and Cost bases, Margin (% of revenue), "Cost is over the NTE", Open the quote, the NTE increases list (Waiting; Approve — set the NTE to $X; Reject; Withdraw); "Your role does not show the money on a work order." when hidden. Timelog: Open for, Response time, Time on site, Paused ("a marker, no clock stops"), Time in each status, the Visits table with Location, Pauses. Related: On this work order chips, the approvals list (NTE override / Status change request / Manager review / Acceptance), Work permits, Same asset and Same site with open counts.',
          value: 'The Facilio parity set for the record, without leaving the page.',
          since: '0064 / 0065',
          deferred: ['The Cost breakdown hint still reads "The final vendor cost, as entered in the Cost field." although Cost now follows the payments.'],
        },
        {
          name: 'Right rail',
          what: 'Responsibility (Vendor "Nobody assigned", Dispatcher "Unassigned", Account manager, Technicians), Location (Site "No site record linked", Asset, Getting in), Time ("On site · live", Open for, In this status, Received, Scheduled, Due, SLA due, First check-in, Last check-out, On site "N over M visits", ETA, Paused) and Cost ("Over NTE", Client NTE, Quote and its status, Invoiced, Cost, Paid out "X of Y", Profit · margin; shown with the money grant), on Overview and the four record tabs.',
          value: 'The numbers a manager asks about, always visible.',
        },
        {
          name: 'Audit trail tab and field history',
          what: 'Every change on this work order, with who, when, how (via visit, approval task, automation, webhook, payment, quote, sign-off, bulk, import) and the before / after; a per-field history panel.',
          value: 'Rule 1.2.1 at the record.',
        },
        {
          name: 'Outside the scope',
          what: 'A work order outside the person\'s Which work orders answers "<WO> is not assigned to you — You see the work orders assigned to you. Ask a manager if you need this one."',
          value: 'The rule is explained, not hidden.',
        },
      ],
    },
    {
      key: 'visits',
      title: 'Visits (CICO) and the quote clock',
      where: 'The CICO tab and the CICO section of All fields.',
      purpose: 'A log of every technician visit with its own check-in and check-out stamps, the status moves that follow and the 48-hour quote clock.',
      value: 'Replaces three free-text fields with a trustworthy log; the quote clock and the On Site moves run themselves.',
      features: [
        {
          name: 'The visit log',
          what: 'New visit: Visit type (Assessment, Job, Return trip; "Pick the visit type first."), Technician (free text, or anyone on file with Hired here / Blacklisted chips), Phone, Method and Method detail ("IVR number, portal, where to submit…"; pre-filled from the FM, or "No check-in method on file for <FM> — add it in Admin › Custom fields"); Log visit. The row\'s status dropdown (Not checked in, Checked in, Checked out, Checked out · return trip needed) stamps the time to the second; the pencil corrects stamps (Save visit; "A corrected time keeps its history"); History of this visit; Delete visit n ("The old check-in/out fields will read the visit before it."). A summary strip: Visits, Time on site, Techs, Last check-out, Quote due; Show all N visits.',
          value: 'Every visit is dated and attributable; the latest one still drives the legacy columns and automations through the mirrored fields.',
          rules: [
            'A check-in moves the work order On Site (Assessment) for an Assessment visit, On Site (Job) for a Job or a Return trip, from whatever status it was in, without asking the status permission; the gates and the Ecotrak check still run and a refusal comes back as a note, never undoing the check-in.',
            'A visit logged straight as checked in stamps now; logged straight as checked out it stamps only the check-out unless a check-in time was given.',
            'A technician picked from the records joins the dispatcher\'s own technician list.',
          ],
          permissions: ['work_orders/fields/cico view / edit + work_orders edit'],
          audit: ['visit_created', 'visit_updated', 'visit_deleted', 'field_updated via visit', 'status_changed via visit'],
          brd: ['2.2.2'],
          since: '0027',
        },
        {
          name: 'Check-in method by FM',
          what: 'An admin table FM → method (IVR, Portal, Email, Operator, App, Manual) with a detail, pre-filling a new visit.',
          value: 'The dispatcher does not have to remember how each facilities-management company wants check-ins done.',
          since: '0028',
        },
        {
          name: 'The quote clock',
          what: 'Quote Due Date = the latest Assessment check-out + 48 wall-clock hours skipping Saturdays, Sundays and the holiday table, in America/Chicago. Re-derived on every visit write; a Job or Return-trip check-out never sets it; cleared when the assessment visit is deleted.',
          value: 'The promise to the client is computed, visible and red when missed, with no hand arithmetic.',
          brd: ['2.3.1', '2.3.2', '2.3.3'],
          since: '0030',
        },
        {
          name: 'Visit location and geofence',
          what: 'On a visit row: Use this device\'s location, or Type coordinates (Latitude / Longitude, Check), Clear; the result reads "<place> · N ft from the pin" against the site\'s pin and boundary, or "Check-in location not recorded".',
          value: 'A check-in far from the site is visible, without a technician app.',
          rules: ['Coordinates are validated (latitude within 90, longitude within 180).'],
          permissions: ['work_orders/fields/cico edit'],
          audit: ['field row "Visit n location"'],
          since: '0064',
        },
      ],
    },
    {
      key: 'signoff',
      title: 'Sign-off sheets',
      where: 'The panel at the foot of the CICO card; GET /api/public/signoff/<token> for the technician.',
      purpose: 'A one-page blank sheet in the billing entity\'s branding, generated when the work order is assigned, texted to the technician, signed on site and texted back into the record.',
      value: 'What the Make + Paperform automation did for ClickUp, with no third-party form: the proof the invoice needs comes back by itself, in the right place.',
      features: [
        {
          name: 'Layouts per billing entity',
          what: 'Comp picks the layout: SFM, TPM, AF ("Job Completion Slip"), RF ("Sign-Off Submission"), EDS, BKR; BKR becomes the EMCOR variant when the client name contains "emcor", and only that layout carries a Closeout Number line. The sheet prints the client\'s WO number (the external reference, else the WO #) and the address, drawn by pdf-lib on US Letter with the entity\'s header, footer and logo; non-Latin text is folded. A work order with no Comp cannot have a sheet ("Set Comp on the work order first").',
          value: 'The client sees its own paperwork, not ours.',
          since: '0070',
        },
        {
          name: 'Generating the sheet',
          what: 'Automatically when the work order is assigned: a created event with an Assignee, or an Assignee change to a non-blank name, draws a sheet when none exists, the Comp maps to a layout and file storage is on (never throws; a re-assignment does not redraw). By hand: Generate sheet (none yet), New sheet, or Redraw with current details when the sheet is stale. The newest sheet is the current one; a new sheet supersedes the old row, deletes its file and its link answers 404. Generation writes the public link into Sign-Off Link.',
          value: 'The sheet exists before anyone asks for it.',
          controls: [
            { label: 'Generate sheet / New sheet / Redraw with current details', does: 'Draws (or redraws) the current sheet.' },
            { label: 'Open / Download / Preview / Hide preview / Open signed copy', does: 'Reads the blank or the signed copy.' },
          ],
          rules: ['Stale ("Details changed") = the WO reference, the address or the layout differs from the work order now.', 'Without file storage: "File storage is not connected on the server (BLOB_READ_WRITE_TOKEN), so no sheet can be drawn or filed."'],
          audit: ['signoff_generated (via button or assignment, with the replaced sheet ids)', 'field_updated on Sign-Off Link via signoff'],
        },
        {
          name: 'Sending it to the technician',
          what: 'Send to tech opens "Send the sign-off sheet": the hired technicians\' phones ("Hired on this work order"), the visit technicians ("Visit n"), the latest visit\'s phone ("Latest visit"), deduplicated, or Another number (Name, Phone). Text the sheet sends through Quo\'s API from the Quo line when the key, the from-number and the Quo switch are set; otherwise Open in Quo hands sms:<phone>?body=… to the Quo desktop app. Either way the share is recorded so the reply can be matched; the share log says "texted from the Quo line" or "through the Quo app". Sharing with no sheet draws one first.',
          value: 'One tap, the technician has the form.',
          rules: ['A number that cannot be normalised is refused ("That is not a phone number we can text"); Quo errors come back as 409s.', 'The public link is a 32-character token, needs no session, serves the PDF inline, is private and not indexed, and dies with its sheet.'],
          permissions: ['work_orders/fields/cico/fields.24. Sign-Off Link view / edit + work_orders view / edit'],
          audit: ['signoff_shared'],
        },
        {
          name: 'The signed copy comes back',
          what: 'A text with a file to the Quo line (message.received) is matched by the sender\'s number to sheets sent to it in the last 45 days (current sheets of live work orders; a signed sheet stays matchable for two days so a second photo lands on the same work order). Exactly one candidate: the file is added as a pending Sign-off attachment by the Quo service principal, Sign-Off Link now points at the attachment and the sheet is marked signed. Several candidates: the file is held and every candidate\'s CICO card shows "A signed sheet came back from a number that holds more than one open sheet. Is it this work order\'s?" with Yes, file it here / Not this one. None: dropped. The chips read Waiting for the signed copy / Signed copy received.',
          value: 'The signature files itself.',
          rules: ['Texts with no file, from an unknown number, or while storage is off are acknowledged and dropped; each file is fetched up to the attachment size cap and must be a PDF or an image.', 'The filed copy still waits for approval on Overview › Photos, and the Done gate for Bill For Incurred reads the APPROVED sign-off.'],
          audit: ['signoff_received', 'signoff_reply_held', 'signoff_reply_dismissed', 'attachment_added (kind signoff, via quo)', 'field_updated on Sign-Off Link'],
          deferred: ['Needs QUO_API_KEY and QUO_FROM_NUMBER on the server for API sends (the Quo desktop fallback works without them) and the message.received event on the Quo webhook.'],
        },
      ],
    },
    {
      key: 'status',
      title: 'Statuses, phases, gates, requests and Ecotrak rules',
      where: 'Change status on the record and in the list; Set status in the bulk bar; Approvals › Status changes; Admin › Custom fields › Statuses.',
      purpose: 'The pipeline as data (statuses in phase groups), the rules that keep a status honest (gates), the request path for dispatcher tiers, and the check against what Ecotrak would allow.',
      value: 'A work order cannot be marked Quote Ready without a quote or Done without proof and cost; dispatchers propose and managers decide; every move is recorded with how it happened.',
      features: [
        {
          name: 'Statuses and phase groups',
          what: 'Statuses are rows with a colour and a position inside phase groups (Open, Active, Pending, Done, Closed and admin-added groups; Ready to Invoice, Done / Incurred and Invoiced are the Done group; Emergency, Approved, Invoiced Not Paid and every custom status sit in Active); each status also maps to a lifecycle phase for the phase bar (Intake, Assessment, Quote, Approval, Scheduled, In Progress, Parts, Done, Invoiced). The code imposes no order: any status may be picked unless a gate or the Ecotrak block refuses it.',
          value: 'The team changes the pipeline in Admin without a deploy; the list tabs and the phase bar follow.',
          permissions: ['admin/fields edit'],
          audit: ['status_created', 'status_updated', 'status_deleted', 'status_group_created', 'status_group_renamed', 'status_group_deleted'],
          since: '0013 / 0020',
        },
        {
          name: 'What a status move does',
          what: 'A single move (header, row pill, approved request, automation, check-in) runs the gates and the Ecotrak check, writes status_changed (with via: visit, approval_task, automation, webhook when the move was not a hand pick; a no-op change writes nothing), stamps Total Invoiced when landing on Invoiced or Invoiced Not Paid, proposes an invoice and a vendor bill when entering the Done group from outside it and an auto-invoice contract covers the work order, re-evaluates the Pulse, closes an open request that asked for this status and an open acceptance when cancelling, and dispatches the automations after the commit. The bulk Set status runs the gates, the Invoiced stamp and the automations only (no Ecotrak check, Pulse or proposals).',
          value: 'One move, every consequence.',
          permissions: ['work_orders/status edit'],
          audit: ['status_changed'],
        },
        {
          name: 'Status change requests',
          what: 'Request-mode roles pick a status and a request lands in Approvals › Status changes (201 raised; a new pick re-targets the open request, 200, and makes the new asker its owner). Approve re-runs the gate and the Ecotrak check, then moves the work order (via approval_task); Reject needs a reason. The requester sees the decision on the header banner ("→ <status> · approved by X" with Continue; "Rejected: <reason>" with Request again / Understood) and in My requests (Withdraw while open, Continue / Understood after); an approver may withdraw or acknowledge on the requester\'s behalf.',
          value: 'Probation and standard dispatchers keep working while managers keep control; nothing waits in Teams.',
          rules: ['A request for the current or an unknown status is refused; a request a gate would refuse is refused up front; approving a request whose target status was deleted is a 409.'],
          permissions: ['work_orders/status create (request)', 'approvals/status approve (decide)'],
          audit: ['approval_task_created', 'approval_task_updated', 'approval_task_approved', 'approval_task_rejected', 'approval_task_cancelled', 'approval_task_acknowledged'],
          brd: ['2.4.1', '2.4.2', '2.4.3', '2.4.4'],
          since: '0031',
        },
        {
          name: 'Gates',
          what: 'Quote Ready needs a quote with at least one line or scope item; Waiting for Parts and Please Order Parts need Parts Required; Done / Incurred needs a visit checked in and out, Cost (zero counts), a quote with data and an approved After photo, or for Bill For Incurred an approved Before photo and an approved Sign-off. The menu tags the pick (Needs quote, Needs parts, Needs check-out, Needs cost, Needs after photo, Needs sign-off, Not ready for several) and the API answers 409 STATUS_GATE with the gate, the status and what is missing; a bulk refusal names the work orders.',
          value: 'The record is complete before it claims to be; AR audits less.',
          rules: ['Gates run on the single move, the bulk move, a request (refused up front), an approval (checked again before it commits), a check-in\'s move and an automation\'s status action (recorded as an errored run); the CSV import is not gated by design.'],
          brd: ['11.2.1', '11.2.2', '11.3.1', '11.3.2', '11.3.3', '11.3.4'],
          since: '0035',
        },
        {
          name: 'Ecotrak allowed transitions',
          what: 'A shared table of what Ecotrak lets a service provider set from each Ecotrak status, and which Ecotrak status each of ours would push (On Site is En route then Arrived). Every single move is checked against the work order\'s Ecotrak Status field: in warn mode (default) the move goes through and a REFUSED verdict is stamped on the status_changed row (allowed moves record nothing); in block mode it is refused ("Ecotrak does not allow Accepted → Arrived (rule 2.6.3)"; requests and approvals prefix "API Violation: Ecotrack does not allow this status transition."). The status menu tags a pick Ecotrak would refuse; the header shows an Ecotrak · <status> chip; inbox rows tag a request Ecotrak would refuse.',
          value: 'When the outbound push goes live the rules are already applied and the refusals already visible.',
          brd: ['2.6.3', '2.6.4', '2.7'],
          deferred: ['Nothing is pushed to Ecotrak until go-live; targets no allowed list names, the "NA" statuses and the soft close as a current state are answered "unlisted", never refused; the bulk Set status skips the check.'],
        },
      ],
    },
    {
      key: 'incoming',
      title: 'Incoming Work Orders: acceptance and drafts',
      where: 'Sidebar › Incoming Work Orders: To accept and Drafts tabs (the strip shows when the person holds both; with one grant the page is that queue).',
      purpose: 'One door for every work order on its way in: the queue a manager accepts from and assigns, and the OP Admin\'s drafting area.',
      value: 'The inbox of client traffic is a queue with a badge, not an email folder; a work order cannot reach a dispatcher half-filled.',
      users: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin', 'Operations Admin'],
      features: [
        {
          name: 'To accept',
          what: 'Every work order the Ecotrak ingest or the CSV import created without an assignee (the Add work order form and the drafts never raise one). Rows read "New work order · From Ecotrak | CSV import · <trade> · accept and assign, or reject" and "Fill before assigning: … · open the work order" while intake fields are missing. Accept opens "Accept this work order?" with Assign to (optgroups Dispatchers / Everyone else), Who\'s available? beside it, and a Note; Accept and assign decides the task and writes the Assignee as the manager\'s own edit ("Assigned to <name>"); Reject ("Reject this work order") needs the reason and moves it to Cancelled / Postponed; Claim takes the row. Every decision posts an internal comment. The header chip reads "Awaiting acceptance · from <source> · since <date> · N intake fields to fill" with Accept or reject for approvers.',
          value: 'Rule 7.1 in one lane: decide fast, assign to the least loaded dispatcher, and never hand over an incomplete work order.',
          rules: ['The assignee must be an active person on file by display name; a reject with no "Cancelled / Postponed" status on file is a 409; filling the Assignee by hand or cancelling closes the task by itself; a row that already has an assignee at creation never enters the queue.'],
          permissions: ['approvals/intake view / approve'],
          audit: ['approval_task_created', 'approval_task_approved', 'approval_task_rejected', 'approval_task_cancelled', 'comment_added', 'field_updated (Assignee)'],
          brd: ['7.1.1', '7.1.2', '7.1.3', '7.1.4'],
          since: '0036',
        },
        {
          name: 'Ready to Assign gate',
          what: 'Received on, Due date, SLA, Address, City, State, Zip code, Store, Trade, WO description, FM, Comp and Client NTE must be filled before Accept and assign, and before a direct or bulk Assignee write while an acceptance is open (checked against the bag as the save leaves it, so filling Address and Assignee together is fine). 409 INTAKE_GATE with the missing labels.',
          value: 'A dispatcher never opens a work order to find the address missing.',
          brd: ['11.1.1', '11.1.2'],
          since: '0037',
        },
        {
          name: 'Drafts (WO Intake)',
          what: 'Columns WO # ("No WO# yet"), Client · Store, Trade, FM, Still to fill, Assignee ("Not assigned"), Last touched; chips Draft / Ready to submit. New work order opens a draft with the WO # ("The client\'s work order number"), the 13 intake fields, Client and Assignee ("Pick the dispatcher it goes to", Who\'s available?); Save draft keeps it; Submit & assign creates the work order already assigned (no acceptance task); Discard this draft? keeps the row as discarded. Result pages Submitted / Discarded with Open the work order / Back to the drafts.',
          value: 'The Operations Admin\'s staging area for emails and phone calls, with the same completeness rule as acceptance.',
          rules: ['Submit refuses (409, rule 14.2.2) until every required field and an active assignee are in, refuses a WO # that exists even in Trash, needs a status named Open, stamps Date Created, inserts like the import (title = first line of the description, promoted columns, Profit), logs created (source intake), runs the create rules, files the SharePoint folder and writes the Assignee as an audited edit.', 'A draft cannot be edited after it is submitted or discarded; discard is idempotent.'],
          permissions: ['intake view / create / edit'],
          audit: ['intake_draft_created', 'intake_draft_updated', 'intake_draft_submitted', 'intake_draft_discarded', 'created (source intake)'],
          brd: ['14.1', '14.3.3'],
          since: '0040',
        },
        {
          name: 'Assignee availability',
          what: 'Beside every Assignee picker (create form, draft, accept, the Assignee seat and the inline editor): For <client> (people listed on the client in Admin › Users) or All dispatchers, each with the number of active work orders across every client, a load bar, a chevron for their work orders per status, Fewest first / Most first, Show everyone else (n) / Only dispatchers. "Active = all of a person\'s open work orders, on every client, not just this one."',
          value: 'Assignment is by load, not by memory.',
          permissions: ['work_orders view'],
        },
      ],
    },
    {
      key: 'approvals',
      title: 'Approvals inbox',
      where: 'Sidebar › Approvals.',
      purpose: 'The manager\'s to-do list: every yes-or-no the system needs from a person, in one sectioned inbox.',
      value: 'Nothing waits in a chat thread; the oldest waits first; escalated rows float to the top; every decision is audited and acted on by the system.',
      users: ['Team Lead', 'Assistant TL', 'Account Manager', 'Admin', 'Accounts Payable'],
      features: [
        {
          name: 'Sections, lanes and filters',
          what: 'Sections All · NTE increases · Status changes · Manager reviews (shown once a task exists) · Quotes · Payments; lanes For me · Open · Done · My requests; filters Entity / Client / Trade / For; a Columns menu (Client, Waiting for, NTE, Cost, WO Due Date, For, Raised, Status, Decision); pagination; up to 500 rows, open first then newest, escalated rows pinned above the waiting lanes. A scoped viewer sees tasks on their own work orders plus their own requests; My requests needs no section grant. Acceptances are never shown here (Incoming Work Orders is their page). Empty states: "Nothing is waiting on you." / "Nothing is waiting for a decision." / "Nothing has been decided yet."',
          value: 'One inbox, each person seeing only the decisions that are theirs.',
          permissions: ['approvals view', 'approvals/nte | status | reviews approve', 'quotes approve + approvals/quotes view', 'payments approve + approvals/payments view'],
          brd: ['7.2.2', '7.2.3', '7.3.3'],
          since: '0026',
        },
        {
          name: 'NTE override',
          what: 'Raised by the seeded rule when Cost rises above the client NTE ("Cost $X is over the client NTE $Y by $Z"; a repeat refreshes the open task, one per work order); while open, quote approve / send and payment approve / send to Yoda are held (409 with the task id; the buttons read "On hold — the NTE override on this work order has to be decided first (rule 1.5.2)"); cancelled by itself once Cost is back under the NTE or either figure is cleared. Decisions post an internal comment.',
          value: 'No money moves past the client\'s ceiling without a manager\'s yes.',
          brd: ['1.5.2'],
        },
        {
          name: 'Deciding',
          what: 'Approve ("Approve this NTE increase / status change / task?", "Approve this quote?" — approving fills the quote amount, sending is a separate step in the builder — "Approve this payment?" — clears it for AP) with an optional Note; Reject ("Why is it being rejected?", Reject with note; titles Return this quote to draft / Reject this payment / Reject this NTE increase / Reject this status change / Reject this task); Claim. Locked verbs say why ("Requires new work order approval rights", the NTE hold). Rows show "Requested by <name>" and the Ecotrak tag on a status request the client system would refuse.',
          value: 'The loop closes on both sides: the decider acts, the requester sees it.',
          rules: ['Approvals raise no bell notice; the manual NTE increase (Cost breakdown tab) does.'],
          audit: ['approval_task_approved', 'approval_task_rejected', 'approval_task_claimed', 'approval_task_cancelled', 'approval_task_acknowledged', 'comment_added'],
        },
        {
          name: 'Badge and counts',
          what: 'The sidebar badge = to decide (open tasks in sections the viewer may approve, plus quotes pending approval and payment requests in requested when the viewer may approve those) + to acknowledge (own decided requests); the Incoming badge carries to accept separately.',
          value: 'The manager knows from any page.',
        },
      ],
    },
    {
      key: 'flags',
      title: 'Emergency and Escalated flags',
      where: 'The work-order header, the Flags tab, every list.',
      purpose: 'Two checkbox fields that colour the work order everywhere it appears.',
      value: 'Urgent work is unmistakable in every list, queue and dashboard, and the escalation route from an email tool is one webhook.',
      features: [
        {
          name: 'Emergency',
          what: 'A checkbox in the Overview section; rows carry it so every list draws the red rail and badge ("Emergency work order") without a second fetch. A paused automation "Rule 2.5.1 · Emergency from client priority" (priority changed to urgent → Emergency) is the hook for the client portals.',
          value: 'The ClickUp "emergency" status becomes a flag that survives every status change.',
          brd: ['2.5.1'],
          since: '0034',
          deferred: ['The Pulse\'s Ack emergency clock keys off the Open / Emergency statuses with high priority, not this flag.'],
        },
        {
          name: 'Escalated',
          what: 'A checkbox the dispatcher tiers cannot edit; Mark as Escalated / Escalated · Clear in the header; amber badge ("Escalated work order — on the Escalation Tracker and pinned to the top of the inbox") and rail (the red rail wins when both); pinned in Approvals; the Escalation Tracker tab. The email webhook (POST /api/webhooks/email-escalation; the secret in x-webhook-secret or a Bearer header; body wo_number, reason, source_email, subject, message_id) sets the flag as the Email escalations service principal and logs the payload; an unknown number is logged and answered 404; it never clears the flag; refused when the Escalation emails integration is off or in DEMO_MODE.',
          value: 'A client escalation is visible to everyone within a minute and tracked until cleared.',
          permissions: ['work_orders/fields/overview/fields.Escalated edit'],
          audit: ['field_updated via webhook', 'escalation_received', 'escalation_unmatched'],
          brd: ['7.3.1', '7.3.2', '7.3.3'],
          since: '0038',
          deferred: ['The webhook secret is not set on the live site yet.'],
        },
      ],
    },
  ],
};
